const fs = require("fs");
const path = require("path");

const BOOKS_PATH = path.join(__dirname, "..", "books.json");

function b(asin, slug, title, author, narrator, coverUrl, duration, durationMinutes, rating, ratingCount, listPrice, categories, tags, description, releaseDate, needsReview, q1, q2, q3, q4, q5) {
  return {
    asin, slug, title, author, narrator, coverUrl,
    duration, durationMinutes, rating, ratingCount,
    listPrice, audiblePrice: 0, isCreditEligible: true, isPlusCatalog: false,
    categories, tags, description, releaseDate,
    binding: "Audible Audiobook", formats: ["Unabridged"],
    detailPageURL: "https://www.amazon.com/dp/" + asin + "?tag=yuanyuan07-20&linkCode=ogi&th=1&psc=1",
    needsReview,
    questions: { q1, q2, q3, q4, q5 }
  };
}

const NEW_BOOKS = [
  b("B07Q4XWX8C", "verity-colleen-hoover", "Verity", "Colleen Hoover", "Vanessa Johansson", "https://m.media-amazon.com/images/I/41xU31AS-BL._SL500_.jpg", "8h 29m", 509, 4.6, 130000, 18.76, ["mystery-thriller", "romance"], ["best-seller", "top-rated"], "Verity is Colleen Hoover's twisty psychological thriller about a struggling writer who takes a job at a bestselling author's mansion and uncovers a chilling manuscript.", "2019-05-07", true,
    "Verity by Colleen Hoover is a psychological thriller about writer Lowen Ashleigh, who discovers a shocking autobiographical manuscript while working for the mysterious author Verity Crawford. Vanessa Johansson narrates this 8.5-hour page-turner.",
    "For thriller fans and Hoover readers who want a fast, twist-heavy listen. It solves the problem of finding a book that is impossible to predict and even harder to put down.",
    "Perfect for commutes, evenings, and weekends; the short chapters and mounting tension make you keep going. You can finish it in a few sessions.",
    "Hoover pivots from romance to full psychological suspense, and the manuscript-within-the-story device keeps you doubting everyone. It is the book that converted many thriller readers to audiobooks.",
    "Absolutely. Start your free trial, and the manuscript reveal in the first hours hooks you completely. The ending will leave you arguing about what really happened."),
  b("B01498HF7E", "the-deal-elle-kennedy", "The Deal", "Elle Kennedy", "Christian Fox", "https://m.media-amazon.com/images/I/51wb0FU5uVL._SL500_.jpg", "9h 24m", 564, 4.5, 70000, 21.50, ["romance"], ["best-seller", "series"], "The Deal is the fan-favorite first Off-Campus novel: a hockey star and a music student fake a relationship to get what they both want.", "2015-11-03", true,
    "The Deal is the first book in Elle Kennedy's Off-Campus series, pairing hockey captain Garrett with tutor Hannah in a fake-dating arrangement. Christian Fox narrates this 9-hour romance.",
    "For sports-romance and fake-dating fans who want banter, steam, and real emotional depth. It solves the problem of finding a romance series that stays fun without getting shallow.",
    "Great for commutes and evenings; the college setting and fast pacing make it easy to binge. A relaxed, entertaining listen.",
    "Garrett and Hannah feel genuinely real, with chemistry that lands in both text and narration. The Deal is widely credited with defining the modern hockey-romance boom.",
    "Absolutely. Start your free trial, and the fake-dating setup hooks you in the first chapters. It is a comfort read you will want to revisit."),
  b("B01496P8T8", "the-mistake-elle-kennedy", "The Mistake", "Elle Kennedy", "Lorelei Avalon", "https://m.media-amazon.com/images/I/51JT7xddt0L._SL500_.jpg", "8h 59m", 539, 4.4, 40000, 20.52, ["romance"], ["best-seller", "series"], "The Mistake is the second Off-Campus novel, following playboy hockey player Logan as he falls for his best friend's younger sister.", "2015-11-03", true,
    "The Mistake is the second Off-Campus book by Elle Kennedy, centered on hockey player Logan and Grace, his best friend's sister. Lorelei Avalon narrates this 9-hour romance.",
    "For Off-Campus fans who want the next brother's story. It solves the problem of a series romance that gives each character a fresh, satisfying arc.",
    "Great for commuting and light listening; the chemistry and humor keep it moving. A fast, fun read.",
    "Logan starts as the classic playboy but earns his redemption, and the friends-to-more dynamic keeps the story grounded. Kennedy's dialogue is a highlight.",
    "Yes. Start your free trial and continue the Off-Campus series. You can start here without reading book one."),
  b("B01M0HY5GY", "the-score-elle-kennedy", "The Score", "Elle Kennedy", "Savannah Peachwood", "https://m.media-amazon.com/images/I/51XfXa7nKLL._SL500_.jpg", "10h 12m", 612, 4.5, 50000, 20.97, ["romance"], ["best-seller", "series"], "The Score is the third Off-Campus novel, where notorious playboy Dean DiLaurentis meets his match in a no-nonsense girl who does not want a relationship.", "2016-09-27", true,
    "The Score is the third Off-Campus novel, following Dean DiLaurentis, the team's charismatic playboy, as he collides with Allie, a girl determined to avoid commitment. Savannah Peachwood narrates.",
    "For fans of opposites-attract and reformed-player romances. It solves the problem of finding a romance with humor, heat, and a genuinely likeable hero.",
    "Great for commutes and weekends; the banter makes it an easy, fun listen. Around 10 hours is perfect for a short binge.",
    "Dean is one of the most beloved heroes in the genre because he is funny, self-aware, and grows on the page. The dual dynamic with Allie keeps the romance fresh.",
    "Absolutely. Start your free trial and let Dean win you over. No series background needed."),
  b("B06XD4BKKP", "the-goal-elle-kennedy", "The Goal", "Elle Kennedy", "Susannah Jones", "https://m.media-amazon.com/images/I/51jF9-cl1JL._SL500_.jpg", "9h 26m", 566, 4.4, 30000, 20.70, ["romance"], ["best-seller", "series"], "The Goal is the fourth Off-Campus novel, pairing single mom Sabrina with hockey player Tucker in a surprisingly tender, steamy story.", "2017-03-06", true,
    "The Goal is the fourth Off-Campus book, following Sabrina, a driven single mother, and Tucker, a hockey player hiding a complicated family life. Susannah Jones narrates.",
    "For romance readers who want more mature stakes, including parenthood and family pressure. It solves the problem of finding a series book with real emotional weight.",
    "Great for evenings and commutes; the balance of warmth and steam keeps it engaging. A comfortable one-credit length.",
    "Kennedy gives her heroine agency and her hero depth beyond the athlete trope. The family dynamics make this one of the series' most grounded entries.",
    "Yes. Start your free trial and meet one of the series' most adult couples. New readers can jump in here."),
  b("B09FQBDTVS", "the-legacy-elle-kennedy", "The Legacy: Off-Campus, Book 5", "Elle Kennedy", "Zachary Webber", "https://m.media-amazon.com/images/I/51OSmINC5rL._SL500_.jpg", "4h 18m", 258, 4.4, 15000, 18.83, ["romance"], ["series"], "The Legacy collects four novellas that catch up with the original Off-Campus couples, giving fans a warm, steamy reunion.", "2021-09-21", true,
    "The Legacy is the fifth Off-Campus entry, a collection of novellas revisiting Garrett, Logan, Dean, and Tucker and their partners. Zachary Webber narrates this shorter listen.",
    "For Off-Campus fans who want to see the original couples again. It solves the problem of finishing a series and wanting more time with beloved characters.",
    "Perfect for a single evening or weekend; each novella is self-contained. A light, rewarding catch-up listen.",
    "Getting four couples in one short collection is a gift for series fans, and the novella format keeps every story tight. It is comfort listening at its best.",
    "Absolutely. Start your free trial and reunite with the Off-Campus crew. Best enjoyed after the first four books."),
  b("B0GL9B9395", "the-divorce-freida-mcfadden", "The Divorce", "Freida McFadden", "January LaVoy", "https://m.media-amazon.com/images/I/41SZNHmFi3L._SL500_.jpg", "10h 0m", 600, 4.5, 5000, 19.32, ["mystery-thriller"], ["new-release", "best-seller"], "The Divorce is Freida McFadden's latest domestic thriller, where a picture-perfect couple's separation uncovers secrets that turn deadly.", "2026-05-26", true,
    "The Divorce is Freida McFadden's newest psychological thriller, exploring a crumbling marriage where nothing is as it seems. January LaVoy narrates this 10-hour listen.",
    "For domestic-thriller fans who love unreliable narrators and twist endings. It solves the problem of finding a fresh McFadden release the moment it is available.",
    "Perfect for commutes and evenings; the short chapters and mounting suspicion make it easy to binge. A fast weekend listen.",
    "McFadden has become a phenomenon by making every chapter end on a hook, and this one leans into the domestic setting that made her famous. LaVoy's narration adds layers of ambiguity.",
    "Absolutely. Start your free trial and let the secrets unfold. If you like Verity and Gone Girl, this fits right in."),
  b("B0FJNF8PP6", "dear-debbie-freida-mcfadden", "Dear Debbie", "Freida McFadden", "Julia Whelan", "https://m.media-amazon.com/images/I/41Uj+OWVSQL._SL500_.jpg", "9h 0m", 540, 4.6, 8000, 18.30, ["mystery-thriller"], ["new-release", "best-seller"], "Dear Debbie is the latest Freida McFadden thriller, told through letters that reveal a friendship hiding dark, life-altering secrets.", "2026-01-27", true,
    "Dear Debbie is Freida McFadden's 2026 thriller, structured around correspondence that exposes the dark side of a lifelong friendship. Julia Whelan narrates this 9-hour listen.",
    "For psychological-thriller fans who love epistolary twists and toxic-friendship stories. It solves the problem of a fresh, format-driven listen from a prolific favorite.",
    "Great for commutes and evenings; the letter structure makes every chapter a new revelation. A fast, gripping listen.",
    "McFadden uses the letter format to create dramatic irony that single-narrator thrillers rarely achieve, and Whelan's performance makes the deception feel intimate.",
    "Absolutely. Start your free trial and open the first letter. The format hooks you immediately."),
  b("B0H8ZJRX1L", "primal-hunter-15-zogarth", "The Primal Hunter 15: A LitRPG Adventure", "Zogarth", "Travis Baldree", "https://m.media-amazon.com/images/I/51np5i4cjTL._SL500_.jpg", "23h 0m", 1380, 4.7, 2000, 34.59, ["fantasy", "sci-fi"], ["new-release", "series", "long-read"], "The Primal Hunter continues in book 15 as Jake pushes his power toward the next threshold in a galaxy of gods, dungeons, and system-driven chaos.", "2026-08-19", true,
    "The Primal Hunter 15 is the latest installment in Zogarth's massive LitRPG series, following Jake as he hunts, levels, and grows stronger across a god-created multiverse. Travis Baldree narrates.",
    "For LitRPG fans who want a long-running series with satisfying progression and a reliable release schedule. It solves the problem of finding a new chapter in a favorite ongoing saga.",
    "Perfect for long commutes and marathon sessions; the progression grind and system mechanics reward dedicated listening. 23 hours is strong value.",
    "Zogarth's world-building is deep, and Baldree's narration has made the series one of the most beloved in LitRPG. Book 15 keeps the momentum of a series with a devoted following.",
    "Absolutely. Start your free trial and catch up on the hunt. New readers should begin with book one for the full journey."),
  b("B0H4LL4PDG", "he-who-fights-with-monsters-13-shirtaloon", "He Who Fights with Monsters 13: A LitRPG Adventure", "Shirtaloon", "Heath Miller", "https://m.media-amazon.com/images/I/51XVeo9KqOL._SL500_.jpg", "24h 0m", 1440, 4.7, 3000, 33.81, ["fantasy", "sci-fi"], ["new-release", "series", "long-read"], "Book 13 of the smash-hit He Who Fights with Monsters continues Jason Asano's irreverent, overpowered journey through the multiverse.", "2026-10-06", true,
    "He Who Fights with Monsters 13 is the next volume in Shirtaloon's hugely popular LitRPG series, following Jason Asano and his crew through new worlds and old enemies. Heath Miller narrates.",
    "For LitRPG readers who love humor, power progression, and ensemble casts. It solves the problem of staying current with one of the genre's biggest ongoing series.",
    "Great for long listening sessions; the witty banter and long arcs reward binge listening. 24 hours per credit is excellent value.",
    "Jason's sarcasm and Heath Miller's narration are a legendary pairing in audiobook LitRPG. The series keeps finding new stakes after a dozen books.",
    "Yes. Start your free trial and join the ongoing saga. New listeners should start at book one to meet Jason properly."),
  b("B0GJ733WZB", "haunting-adeline-carlton", "Haunting Adeline: Cat and Mouse Duet, Book 1", "H. D. Carlton", "Teddy Hamilton", "https://m.media-amazon.com/images/I/51eBvDm-gWL._SL500_.jpg", "14h 25m", 865, 4.5, 50000, 25.72, ["romance"], ["best-seller", "dark-romance", "series"], "Haunting Adeline is the viral dark romance where a stalker's obsession becomes a twisted, all-consuming love story.", "2026-01-22", true,
    "Haunting Adeline is the first book in H.D. Carlton's Cat and Mouse duet, a dark romance centered on Adeline and the dangerously obsessive man who hunts her. Teddy Hamilton narrates.",
    "For dark-romance readers who love stalker tropes, high heat, and morally gray heroes. It solves the problem of finding the book that dominates dark-romance recommendations.",
    "Best for evening listening with privacy; the content is intense. 14 hours fits comfortably in a trial week.",
    "This book defines modern dark romance for many listeners, with a hero who is genuinely dangerous and a heroine who fights back. Hamilton's performance is a favorite among audiobook fans.",
    "Absolutely. Start your free trial and step into the cat-and-mouse game. Check trigger warnings first, then let it consume you."),
  b("B0GJ7336RD", "hunting-adeline-carlton", "Hunting Adeline: Cat and Mouse Duet, Book 2", "H. D. Carlton", "Teddy Hamilton", "https://m.media-amazon.com/images/I/51EhezovJkL._SL500_.jpg", "16h 58m", 1018, 4.6, 45000, 27.06, ["romance"], ["best-seller", "dark-romance", "series"], "Hunting Adeline concludes the Cat and Mouse duet, following the brutal hunt to rescue Adeline and the reckoning that follows.", "2026-01-22", true,
    "Hunting Adeline is the second Cat and Mouse book, a darker, more violent continuation as the hunt for Adeline becomes a rescue mission and a revenge saga. Teddy Hamilton narrates.",
    "For readers who finished Haunting Adeline and need the conclusion. It solves the problem of an unfinished dark-romance arc and delivers the payoff fans demanded.",
    "Best for focused, mature listening sessions. At 17 hours, it is a substantial binge with high emotional stakes.",
    "The duet becomes more action-thriller in the second half, giving the romance a relentless, cinematic energy. Hamilton's narration keeps the intensity high.",
    "Yes. Start your free trial and complete the duet. The ending is cathartic for readers who loved book one."),
  b("B0FL2T86WF", "lights-out-navessa-allen", "Lights Out: An Into Darkness Novel", "Navessa Allen", "Elena Wolfe", "https://m.media-amazon.com/images/I/511goxUI+CL._SL500_.jpg", "11h 0m", 660, 4.6, 30000, 21.60, ["romance"], ["best-seller", "dark-romance"], "Lights Out is the viral dark romance with a stalker twist and a heartbreakingly soft hero, dominating dark-romance lists since release.", "2025-08-04", true,
    "Lights Out by Navessa Allen is a dark romance that went viral, pairing a woman with a dangerously obsessive man who turns out to be far softer than expected. Elena Wolfe narrates.",
    "For dark-romance readers who want the genre's most talked-about recent hit. It solves the problem of finding a book with both edge and heart.",
    "Great for evening listening and weekends; the tension and humor make it hard to pause. 11 hours is a perfect binge length.",
    "The male lead became a fan favorite because he is intense yet unexpectedly gentle, flipping dark-romance expectations. The audiobook's narration captures both sides.",
    "Absolutely. Start your free trial and see why this book took over dark-romance feeds. Trigger warnings apply, then enjoy the ride."),
  b("B0FGK61PVG", "insatiable-leigh-rivers", "Insatiable: The Edge of Darkness, Book 1", "Leigh Rivers", "Teddy Hamilton", "https://m.media-amazon.com/images/I/51IXlKFV5NL._SL500_.jpg", "12h 0m", 720, 4.5, 20000, 21.39, ["romance"], ["dark-romance", "series"], "Insatiable opens Leigh Rivers' Edge of Darkness series, a dark, possessive romance wrapped in secrets and obsession.", "2025-07-31", true,
    "Insatiable is the first book in Leigh Rivers' Edge of Darkness series, a dark romance full of obsession, secrets, and morally gray desire. Teddy Hamilton narrates.",
    "For dark-romance readers who want a new series with possessive heroes and slow-burn tension. It solves the problem of finding a fresh voice after the genre's big hits.",
    "Great for evening listening; the psychological tension rewards focus. A solid 12-hour commitment.",
    "Rivers builds a moody, layered world with characters who feel genuinely dangerous, and Hamilton's performance deepens the pull. A strong series opener.",
    "Absolutely. Start your free trial and enter the Edge of Darkness. Dark-romance fans will feel right at home."),
  b("B0GN9B5DQ4", "daggermouth-hm-wolfe", "Daggermouth", "H. M. Wolfe", "Teddy Hamilton", "https://m.media-amazon.com/images/I/513iOJTlC4L._SL500_.jpg", "13h 0m", 780, 4.5, 5000, 26.24, ["romance"], ["dark-romance", "new-release"], "Daggermouth is H.M. Wolfe's new dark romance, blending an assassin's ruthlessness with an unexpected, consuming love story.", "2026-06-30", true,
    "Daggermouth by H.M. Wolfe is a 2026 dark romance centered on an assassin with a deadly reputation and the person who sees through it. Teddy Hamilton narrates.",
    "For dark-romance fans who love killers with hidden softness and high-heat tension. It solves the problem of finding a fresh, edgy release.",
    "Best for evening sessions; the moody tone rewards focused listening. Around 13 hours is a comfortable commitment.",
    "Wolfe leans into the morally gray hero archetype with real craft, and Hamilton's dual-performance energy makes the contrast between violence and tenderness land.",
    "Absolutely. Start your free trial and meet Daggermouth. Dark-romance readers will be hooked early."),
  b("B0G4XWJQ79", "rites-of-the-starling-devney-perry", "Rites of the Starling: Shield of Sparrows, Book 2", "Devney Perry", "Jason Clarke", "https://m.media-amazon.com/images/I/51DJtbIL5lL._SL500_.jpg", "11h 0m", 660, 4.6, 10000, 26.79, ["romance"], ["series", "new-release"], "Rites of the Starling continues Devney Perry's Shield of Sparrows series, a romantic suspense saga with a hidden identity at its core.", "2026-04-07", true,
    "Rites of the Starling is the second book in Devney Perry's Shield of Sparrows series, continuing a romantic suspense story around a woman living under an assumed identity. Jason Clarke narrates.",
    "For romantic-suspense fans who love secrets, small-town tension, and slow-burn romance. It solves the problem of finding a series that rewards following along.",
    "Great for evenings and weekends; the suspense threads keep momentum. A comfortable 11-hour listen.",
    "Perry is a master of small-town romantic suspense, and the found-family and mystery layers make this series a standout. Clarke brings warmth to the protective hero.",
    "Absolutely. Start your free trial and continue the Shield of Sparrows story. New readers can start with book one for full context."),
  b("B0FQQFHHW6", "starside-alex-aster", "Starside: A Novel", "Alex Aster", "Vanessa Moyen", "https://m.media-amazon.com/images/I/51x97mDGPgL._SL500_.jpg", "16h 0m", 960, 4.5, 8000, 41.39, ["fantasy", "romance"], ["new-release", "best-seller"], "Starside is Alex Aster's high-stakes romantasy debut, blending a deadly contest, forbidden magic, and a love that could end the world.", "2026-03-31", true,
    "Starside by Alex Aster is a 2026 romantasy novel with a deadly contest, dark magic, and a morally complex romance. Vanessa Moyen narrates this 16-hour epic.",
    "For romantasy fans who loved Fourth Wing and The Cruel Prince and want a fresh, cinematic new series. It solves the problem of finding the next big romantasy debut.",
    "Great for long sessions and weekends; the contest structure and political tension reward binge listening. 16 hours is strong value.",
    "Aster, already known for young-adult fantasy, brings sharp pacing and high-stakes romance to adult romantasy. Moyen's narration captures both the danger and the chemistry.",
    "Absolutely. Start your free trial and enter the Starside contest. New-series fans will be in early on a likely phenomenon."),
  b("B0FVMTQXG4", "the-shampoo-effect-jenny-jackson", "The Shampoo Effect: A Read with Jenna Pick: A Novel", "Jenny Jackson", "Marin Ireland", "https://m.media-amazon.com/images/I/51l31uYDaKL._SL500_.jpg", "10h 0m", 600, 4.3, 10000, 19.80, ["fiction", "romance"], ["new-release", "book-club"], "The Shampoo Effect is Jenny Jackson's witty, big-hearted novel about beauty, money, and the complicated bonds between three sisters.", "2026-06-30", true,
    "The Shampoo Effect by Jenny Jackson is a 2026 literary novel about three sisters navigating wealth, beauty, and family loyalty. Marin Ireland narrates this 10-hour read.",
    "For readers who love sharp, character-driven women's fiction and family dramas. It solves the problem of finding a smart, entertaining book-club pick.",
    "Great for commutes and evenings; the ensemble cast keeps every chapter engaging. A satisfying week-long listen.",
    "Jackson brings the warm wit of her bestselling debut, Pineapple Street, into a beauty-industry family saga. Ireland's narration balances humor and heartbreak.",
    "Absolutely. Start your free trial and meet the sisters. It is a warm, insightful listen for any book club."),
  b("B0GZWPZL1V", "a-very-good-bad-idea-emma-chase", "A Very Good Bad Idea", "Emma Chase", "Sean Masters", "https://m.media-amazon.com/images/I/51PT1HkuxUL._SL500_.jpg", "8h 0m", 480, 4.4, 15000, 18.65, ["romance"], ["new-release", "rom-com"], "A Very Good Bad Idea is Emma Chase's new romantic comedy about falling for the brother of the groom at a wedding that keeps going wrong.", "2026-07-09", true,
    "A Very Good Bad Idea by Emma Chase is a 2026 romantic comedy about a wedding, a meddling ex, and a heroine who falls for the groom's brother. Sean Masters narrates.",
    "For rom-com fans who love wedding chaos and forbidden-adjacent attraction. It solves the problem of finding a light, funny listen with real heart.",
    "Perfect for commutes and weekends; the humor and fast pacing make it an easy, joyful binge. A great palate cleanser.",
    "Emma Chase writes banter that lands, and the wedding setting gives the comedy perfect timing. The audiobook's dual narration keeps the chemistry crackling.",
    "Absolutely. Start your free trial and RSVP to the chaos. Rom-com fans will finish it in a day or two."),
  b("B0H9ZBC6CV", "just-for-the-plot-meghan-quinn", "Just for the Plot", "Meghan Quinn", "Samantha Brentmoor", "https://m.media-amazon.com/images/I/51u3PMPoKTL._SL500_.jpg", "10h 0m", 600, 4.6, 10000, 22.79, ["romance"], ["new-release", "rom-com"], "Just for the Plot is Meghan Quinn's new Hollywood rom-com about a screenwriter and an actor pretending to date for a role.", "2026-07-28", true,
    "Just for the Plot by Meghan Quinn is a 2026 Hollywood rom-com about a fake relationship between a screenwriter and an actor auditioning for a role. Samantha Brentmoor narrates.",
    "For rom-com fans who love showbiz settings, fake dating, and laugh-out-loud dialogue. It solves the problem of finding a fresh, fun release from a reliable favorite.",
    "Great for commutes and light evenings; the banter keeps it moving. A fast, feel-good listen.",
    "Quinn is a rom-com powerhouse, and the movie-making premise gives the fake-dating trope new material. Brentmoor brings both wit and warmth.",
    "Absolutely. Start your free trial and watch the sparks fly on set. Rom-com readers will devour it."),
  b("B0DFMZMKFJ", "the-let-them-theory-mel-robbins", "The Let Them Theory: A Life-Changing Tool", "Mel Robbins", "Mel Robbins", "https://m.media-amazon.com/images/I/51YOr6ua-PL._SL500_.jpg", "7h 30m", 450, 4.7, 30000, 20.97, ["self-improvement"], ["best-seller", "top-rated"], "The Let Them Theory is Mel Robbins' viral mindset framework for letting go of what you cannot control and reclaiming your energy.", "2024-12-24", true,
    "The Let Them Theory by Mel Robbins is the viral self-development audiobook built around one simple idea: let other people be who they are so you can focus on what you control. Robbins narrates it herself.",
    "For anyone exhausted by people-pleasing, overthinking, or trying to manage others' reactions. It solves the problem of boundary-setting with a memorable, repeatable tool.",
    "Perfect for commutes, walks, and mornings; the short chapters and real-life examples make it easy to apply daily. A fast, actionable listen.",
    "Robbins' straight-talk style and personal stories make psychology practical, and her own narration adds credibility. The 'Let Them' phrase has become a genuine cultural tool.",
    "Absolutely. Start your free trial, and you can use the tool before you finish the first chapter. It is the rare self-help book you will apply the same day."),
  b("B0FPGMSSQK", "dolly-all-the-time-annabel-monaghan", "Dolly All the Time: A GMA Book Club Pick", "Annabel Monaghan", "Julia Whelan", "https://m.media-amazon.com/images/I/51nQbL7rN6L._SL500_.jpg", "8h 0m", 480, 4.5, 8000, 19.80, ["fiction", "romance"], ["new-release", "book-club"], "Dolly All the Time is Annabel Monaghan's witty novel about a mother finding herself after the kids leave, with a little help from Dolly Parton's spirit.", "2026-05-26", true,
    "Dolly All the Time by Annabel Monaghan is a 2026 book-club favorite about a recently emptied nest, a struggling marriage, and a heroine rediscovering herself with Dolly Parton as her guide. Julia Whelan narrates.",
    "For readers who love warm, funny women's fiction about reinvention. It solves the problem of a feel-good read with real emotional depth.",
    "Great for commutes and cozy weekends; the humor and heart keep it light. A perfect palate-cleanser listen.",
    "Monaghan pairs a relatable midlife story with the joyful spirit of Dolly Parton, and Whelan's narration makes the warmth land. It is uplifting without being saccharine.",
    "Absolutely. Start your free trial and let Dolly work her magic. Book-club readers will love discussing it."),
  b("B0F6QPJMKJ", "strangers-belle-burden", "Strangers: A Memoir of Marriage", "Belle Burden", "Belle Burden", "https://m.media-amazon.com/images/I/41AD8DWkHRL._SL500_.jpg", "7h 0m", 420, 4.4, 5000, 19.80, ["biographies-memoirs"], ["new-release", "memoir"], "Strangers is Belle Burden's intimate memoir about a marriage that becomes a stranger to itself, and the slow, honest work of finding each other again.", "2026-01-13", true,
    "Strangers by Belle Burden is a memoir about watching a long marriage become unrecognizable and the painful, honest path back toward each other. Burden narrates her own story.",
    "For readers who love intimate, reflective memoirs about love and family. It solves the problem of finding a quiet book that sits with you after it ends.",
    "Best for calm evenings and weekend listening; the reflective tone rewards unhurried sessions. A manageable 7-hour commitment.",
    "Burden writes about marriage with unusual honesty, avoiding easy villains or tidy answers. The author's own narration makes every line feel lived-in.",
    "Absolutely. Start your free trial and step into the story. Memoir lovers will find it quietly powerful."),
  b("B0GZ83XXZC", "the-janitor-don-winslow", "The Janitor", "Don Winslow", "Titus Welliver", "https://m.media-amazon.com/images/I/51-zy9p1fJL._SL500_.jpg", "5h 0m", 300, 4.5, 20000, 13.54, ["mystery-thriller"], ["new-release", "best-seller"], "The Janitor is Don Winslow's short, explosive thriller about a Marine-turned-janitor with lethal skills, narrated by Titus Welliver.", "2026-07-16", true,
    "The Janitor by Don Winslow is a taut, action-packed thriller about a former Marine who works as a janitor until someone makes a fatal mistake. Titus Welliver narrates this 5-hour listen.",
    "For thriller fans who want a short, high-octane listen with a memorable hero. It solves the problem of a quick read that still delivers Winslow's punch.",
    "Perfect for a single evening or a long flight; the lean pacing makes it a one-sitting listen. Great value in a short window.",
    "Winslow writes propulsive action better than almost anyone, and Welliver's gravelly voice is ideal for the vigilante-janitor premise. It is pure, satisfying pulp.",
    "Absolutely. Start your free trial and finish it in one evening. Thriller fans will love the efficiency."),
];

const data = JSON.parse(fs.readFileSync(BOOKS_PATH, "utf-8"));
const existing = new Set(data.books.map((b) => b.asin));
let added = 0;
for (const book of NEW_BOOKS) {
  if (!existing.has(book.asin)) {
    data.books.push(book);
    existing.add(book.asin);
    added++;
    console.log("Added " + book.slug);
  } else {
    console.log("Skip existing " + book.asin);
  }
}
fs.writeFileSync(BOOKS_PATH, JSON.stringify(data, null, 2));
console.log("Batch 3 complete. Added " + added + " books. Total: " + data.books.length);
