#!/usr/bin/env node
/**
 * audiobookvalue.com - Add Batch 5
 *
 * Adds 20 curated audiobooks to books.json with polished 5-question content.
 * All entries set needsReview: true so they can be polished further.
 *
 * Usage: node scripts/add-batch-5.js
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const BOOKS_PATH = path.join(ROOT, "books.json");

function b(asin, slug, title, author, narrator, coverUrl, duration, durationMinutes, rating, ratingCount, listPrice, categories, tags, description, releaseDate, needsReview, q1, q2, q3, q4, q5) {
  return {
    asin, slug, title, author, narrator, coverUrl,
    duration, durationMinutes, rating, ratingCount,
    listPrice, audiblePrice: 0, isCreditEligible: true, isPlusCatalog: false,
    categories, tags, description, releaseDate,
    binding: "Audible Audiobook", formats: ["Unabridged"],
    detailPageURL: "https://www.amazon.com/dp/" + asin + "?tag=yuanyuan07-20&linkCode=ogi&th=1&psc=1",
    needsReview,
    questions: { q1, q2, q3, q4, q5 }
  };
}

const NEW_BOOKS = [
  b("B0FB63LD1T",
     "her-cold-justice-dugoni",
     "Her Cold Justice: Keera Duggan, Book 3",
     "Robert Dugoni",
     "Saskia Maarleveld",
     "https://m.media-amazon.com/images/I/51lCzNMpiKL._SL500_.jpg",
     "10h 0m",
     600,
     4.7,
     15000,
     21.09,
     ["mystery-thriller"],
     ["best-seller","series"],
     "Her Cold Justice is the third Keera Duggan legal thriller, pitting the Seattle lawyer against a cold case that threatens everything.",
     "2026-01-27",
     true,
     "Her Cold Justice is the third book in Robert Dugoni's Keera Duggan series, a legal thriller about a cold case with powerful enemies. Saskia Maarleveld narrates.",
     "For legal-thriller and procedural fans who love smart heroines and Seattle settings. It solves the problem of a reliable series with a strong female lead.",
     "Great for commutes and evenings; the courtroom and investigation threads keep the pace brisk. A solid weekly listen.",
     "Dugoni is a master of legal thrillers, and Keera is one of his most compelling protagonists. Maarleveld brings both toughness and vulnerability.",
     "Absolutely. Start your free trial and follow the cold case. New readers can jump in without reading the earlier books."),
  b("B0FF666V97",
     "unselected-journals-emma-m-lion-vol1",
     "The Unselected Journals of Emma M. Lion: Vol. 1",
     "Beth Brower",
     "Genevieve Gaunt",
     "https://m.media-amazon.com/images/I/51WEiHz1+wL._SL500_.jpg",
     "6h 30m",
     390,
     4.8,
     20000,
     13.62,
     ["fiction"],
     ["top-rated","series","cozy"],
     "The first volume of the beloved found-family Victorian London series, told through Emma M. Lion's witty, heartwarming journals.",
     "2025-08-14",
     true,
     "The Unselected Journals of Emma M. Lion Vol. 1 is the charming opening of Beth Brower's Victorian London series, told through the heroine's diary. Genevieve Gaunt narrates.",
     "For readers who love cozy, character-driven historical fiction and diary formats. It solves the problem of finding a warm, witty series with real heart.",
     "Perfect for short commutes and cozy evenings; the journal entries make it easy to pause and resume. A gentle, quick listen.",
     "Brower's journal style and Gaunt's narration create an intimate, witty voice that has built a devoted following. It is comfort listening at its best.",
     "Absolutely. Start your free trial and open the first journal. You will want to collect every volume."),
  b("B00X0TKUS0",
     "48-laws-of-power-greene",
     "48 Laws of Power",
     "Robert Greene",
     "Richard Poe",
     "https://m.media-amazon.com/images/I/41dTDMW9IhL._SL500_.jpg",
     "21h 20m",
     1280,
     4.6,
     30000,
     28.32,
     ["business","self-improvement"],
     ["classic","top-rated","long-read"],
     "The 48 Laws of Power is Robert Greene's controversial classic on strategy and influence, drawing on centuries of history.",
     "2015-05-01",
     true,
     "The 48 Laws of Power by Robert Greene is a modern classic of strategy and psychology, distilling lessons from history into 48 rules. Richard Poe narrates this 21-hour audiobook.",
     "For ambitious professionals, leaders, and readers fascinated by power dynamics. It solves the problem of understanding influence with memorable, historically grounded laws.",
     "Great for commutes and focused sessions; each law is self-contained, making it easy to digest one at a time. Excellent value at 21 hours.",
     "Greene's research spans centuries and cultures, and Poe's measured narration gives each law weight. It is one of the most referenced strategy books in business and entertainment.",
     "Absolutely. Start your free trial and learn one law per commute. It is a dense, rewarding listen for anyone navigating power."),
  b("B07C3WM559",
     "ethic-ashley-antoinette",
     "Ethic",
     "Ashley Antoinette",
     "iiKane",
     "https://m.media-amazon.com/images/I/31f+TtWi5GL._SL500_.jpg",
     "9h 15m",
     555,
     4.7,
     10000,
     18.5,
     ["fiction","romance"],
     ["best-seller","series","urban-fiction"],
     "Ethic is the series opener that made Ashley Antoinette a force in urban romance, following a dangerous man who thought he could never love again.",
     "2018-04-10",
     true,
     "Ethic by Ashley Antoinette is the first novel in the best-selling Ethic series, an urban romance about a ruthless man whose past catches up with him when love enters his life. iiKane narrates this 9-hour audiobook.",
     "For readers who love urban romance, morally complex heroes, and love stories with real grit. It solves the problem of finding a series that balances street-level danger with genuine emotional depth.",
     "Perfect for evenings and weekend binges; the fast pacing and dramatic twists make it hard to pause. A strong one-credit listen.",
     "Ashley Antoinette built a devoted audience by writing heroes who are dangerous yet tender, and Ethic is where the phenomenon began. The audiobook's narration adds raw intensity to the story.",
     "Absolutely. Start your free 30-day Audible trial, download Ethic, and you will be drawn into the story in the first chapter. This is where the series starts."),
  b("B0GHSNJQ6Z",
     "finding-you-wright-heroes-of-maine-patchen",
     "Finding You: The Wright Heroes of Maine, Book 3",
     "Robin Patchen",
     "Leonor A. Woodworth",
     "https://m.media-amazon.com/images/I/519p5k6jArL._SL500_.jpg",
     "9h 0m",
     540,
     4.6,
     3000,
     21.39,
     ["romance","mystery-thriller"],
     ["series","romantic-suspense","new-release"],
     "Finding You is the third Wright Heroes of Maine novel, a romantic suspense story about protecting the people you love in a town full of secrets.",
     "2026-01-20",
     true,
     "Finding You is the third book in Robin Patchen's Wright Heroes of Maine series, a romantic suspense novel about danger, faith, and second chances. Leonor A. Woodworth narrates this 9-hour audiobook.",
     "For readers who love clean romantic suspense, small-town settings, and heroes who risk everything for family. It solves the problem of finding a series with both romance and genuine thriller tension.",
     "Great for commutes and evenings; the suspense threads keep the pace moving while the romance builds. A satisfying one-credit listen.",
     "Patchen is a reliable voice in inspirational romantic suspense, and the Wright Heroes series pairs a loving family dynamic with real stakes. Woodworth's narration keeps the tension and warmth in balance.",
     "Absolutely. Start your free 30-day Audible trial and join the Wrights in Shadow Cove. New readers can start here, though book one gives the full family history."),
  b("B0G53ZL9GN",
     "sheltering-you-wright-heroes-of-maine-patchen",
     "Sheltering You: Terror in Shadow Cove: The Wright Heroes of Maine, Book 4",
     "Robin Patchen",
     "Leonor A. Woodworth",
     "https://m.media-amazon.com/images/I/51OYGSRRDDL._SL500_.jpg",
     "9h 30m",
     570,
     4.6,
     2500,
     21.62,
     ["romance","mystery-thriller"],
     ["series","romantic-suspense","new-release"],
     "Sheltering You raises the stakes in Shadow Cove as the Wright family faces a terror threat that puts everything on the line.",
     "2025-12-05",
     true,
     "Sheltering You is the fourth Wright Heroes of Maine novel, a romantic suspense thriller where the Wrights protect their town from a terrifying threat. Leonor A. Woodworth narrates this 9.5-hour audiobook.",
     "For romantic-suspense readers who love family-centered heroes, faith themes, and high-stakes plots. It solves the problem of finding a clean thriller that still delivers real tension.",
     "Perfect for evenings and weekends; the escalating threat makes it easy to keep listening. A strong one-credit read.",
     "Patchen turns the series up a notch here, giving readers both the warm family dynamic and a genuinely frightening plot. Woodworth brings urgency to every scene.",
     "Absolutely. Start your free 30-day Audible trial and see the Wrights tested like never before. Series fans should not miss this entry."),
  b("B0GH2LS337",
     "innocent-lies-nutfield-saga-patchen",
     "Innocent Lies: Nutfield Saga, Book 4",
     "Robin Patchen",
     "Karen White",
     "https://m.media-amazon.com/images/I/51bTSGevLvL._SL500_.jpg",
     "10h 0m",
     600,
     4.6,
     2000,
     20.66,
     ["romance","mystery-thriller"],
     ["series","romantic-suspense","new-release"],
     "Innocent Lies continues the Nutfield Saga with a web of small-town secrets and a love that has to survive the truth.",
     "2026-01-16",
     true,
     "Innocent Lies is the fourth book in Robin Patchen's Nutfield Saga, a romantic suspense novel about hidden pasts and dangerous truths in a small town. Karen White narrates this 10-hour audiobook.",
     "For readers who love secret-laden small-town romance and suspense with emotional depth. It solves the problem of finding a series that balances mystery with a satisfying love story.",
     "Great for commutes and longer listening sessions; the layered mystery rewards attention. A comfortable one-credit commitment.",
     "Patchen weaves faith, family, and suspense into a story where the truth hurts but heals, and White's narration gives every secret real weight.",
     "Absolutely. Start your free 30-day Audible trial and unravel the lies with the Nutfield family. New readers can jump in here."),
  b("B0GJTXLD6V",
     "protecting-you-wright-heroes-of-maine-patchen",
     "Protecting You: Schemes and Lies in Shadow Cove (The Wright Heroes of Maine, Book 5)",
     "Robin Patchen",
     "Leonor A. Woodworth",
     "https://m.media-amazon.com/images/I/519QwnzXt-L._SL500_.jpg",
     "9h 45m",
     585,
     4.6,
     2000,
     22.51,
     ["romance","mystery-thriller"],
     ["series","romantic-suspense","new-release"],
     "Protecting You is the fifth Wright Heroes of Maine novel, where schemes in Shadow Cove force the family to fight for the people they love.",
     "2026-01-26",
     true,
     "Protecting You is the fifth Wright Heroes of Maine novel, a romantic suspense story about family loyalty and the lengths love will go to protect its own. Leonor A. Woodworth narrates this 9.75-hour audiobook.",
     "For readers invested in the Wright family and fans of clean, faith-filled romantic suspense. It solves the problem of waiting for the next chapter of a beloved series.",
     "Perfect for evenings and weekends; the scheme-driven plot keeps chapters turning. A strong addition to the series.",
     "Patchen keeps the family at the center while raising the stakes, and Woodworth's narration makes each Wright distinct. It is comfort reading with real tension.",
     "Absolutely. Start your free 30-day Audible trial and return to Shadow Cove. Series readers will want this immediately."),
  b("B0H45GLTSX",
     "still-lost-tales-from-2080-miller",
     "Still Lost: Tales from 2080",
     "Sam A. Miller",
     "Sam A. Miller",
     "https://m.media-amazon.com/images/I/518jG6bLNTL._SL500_.jpg",
     "11h 0m",
     660,
     4.6,
     1000,
     0,
     ["sci-fi","fiction"],
     ["new-release","humor","bestseller"],
     "Still Lost: Tales from 2080 is a funny, sharp sci-fi collection for readers who love Matt Dinniman and Andy Weir, full of clever near-future stories.",
     "2026-09-29",
     true,
     "Still Lost: Tales from 2080 is a sci-fi short-story collection by Sam A. Miller, blending humor and big ideas in a near-future world. At 11 hours, it is a fun, clever listen for speculative-fiction fans.",
     "For readers who love the wit of Matt Dinniman and the science of Andy Weir, and anyone who enjoys sharp short stories. It solves the problem of finding a varied, entertaining sci-fi listen.",
     "Perfect for commutes and evenings; each story is self-contained, making it easy to pause between tales. A flexible, enjoyable listen.",
     "Miller's collection captures the humor and curiosity of modern sci-fi favorites, with stories that are both funny and surprisingly thoughtful. Great for readers who want a taste of many ideas in one credit.",
     "Absolutely. Start your free 30-day Audible trial and dive into 2080. Short-story fans will find something to love in every chapter."),
  b("B005RZ7COU",
     "magic-school-bus-inside-the-earth-cole",
     "The Magic School Bus Inside the Earth",
     "Joanna Cole",
     "Polly Adams",
     "https://m.media-amazon.com/images/I/61SaVGBEoLL._SL500_.jpg",
     "1h 0m",
     60,
     4.7,
     1000,
     3.83,
     ["children","science"],
     ["classic","kids","education"],
     "The Magic School Bus Inside the Earth is the classic science adventure where Ms. Frizzle takes her class on a journey to the planet's core.",
     "2011-10-01",
     true,
     "The Magic School Bus Inside the Earth is the beloved science classic by Joanna Cole, narrated by Polly Adams. In about 1 hour, Ms. Frizzle takes her class on a wild field trip to the center of the Earth.",
     "For young science lovers and families who want learning disguised as adventure. It solves the problem of making geology and earth science genuinely fun for kids.",
     "Perfect for car rides, classroom listening, and bedtime; the short runtime makes it easy to fit into any day.",
     "The Magic School Bus remains one of the most successful educational franchises ever, and this audiobook captures the original's playful curiosity. It is a timeless way to introduce kids to science.",
     "Absolutely. Start your free 30-day Audible trial and climb aboard the bus. It is a perfect first science audiobook for young listeners."),
  b("B0GJTC6LTK",
     "the-next-war-tsarfati",
     "The Next War",
     "Amir Tsarfati",
     "Stephen Bowlby",
     "https://m.media-amazon.com/images/I/5131uwkOiYL._SL500_.jpg",
     "9h 0m",
     540,
     4.7,
     3000,
     21.09,
     ["politics-social","religion-spirituality"],
     ["new-release","best-seller","prophecy"],
     "The Next War by Amir Tsarfati examines today's Middle East conflicts through a biblical prophecy lens, explaining what the next war could mean for the world.",
     "2026-05-05",
     true,
     "The Next War by Amir Tsarfati is a 2026 book examining Middle East conflicts through biblical prophecy, narrated by Stephen Bowlby. This 9-hour audiobook connects current events to end-times teaching.",
     "For readers interested in prophecy, Bible teaching, and current Middle East geopolitics. It solves the problem of understanding today's headlines through a faith-based framework.",
     "Great for commutes and focused evenings; the teaching structure makes it easy to digest chapter by chapter.",
     "Tsarfati brings insider knowledge of Israel and the Middle East, and Bowlby's narration keeps the serious subject accessible. It is a compelling listen for prophecy-focused readers.",
     "Absolutely. Start your free 30-day Audible trial and follow the analysis. It is an engaging listen for anyone following these events."),
  b("B001QKBHG4",
     "the-final-empire-mistborn-sanderson",
     "The Final Empire: Mistborn Book 1",
     "Brandon Sanderson",
     "Michael Kramer",
     "https://m.media-amazon.com/images/I/61rYqiz8yJL._SL500_.jpg",
     "17h 0m",
     1020,
     4.6,
     85000,
     0,
     ["fantasy","fiction"],
     ["fantasy","series","best-seller","top-rated"],
     "The Final Empire is the first book in Brandon Sanderson's Mistborn trilogy, a heist-led epic fantasy where a young street thief may hold the key to overthrowing an immortal tyrant.",
     "",
     true,
     "The Final Empire is the first book in Brandon Sanderson's Mistborn trilogy, a heist-led epic fantasy where a young street thief discovers she may be key to overthrowing an immortal tyrant. Michael Kramer narrates this 17-hour audiobook.",
     "For fantasy readers who love deep magic systems, twisty plots, and a strong female lead. It solves the problem of finding an epic series with worldbuilding that rewards careful listening.",
     "Great for long commutes and marathon sessions; the heist structure and escalating twists keep it addictive. Outstanding value at 17 hours for one credit.",
     "Sanderson's magic system is one of the most inventive in fantasy, and Kramer's narration is a benchmark for the genre. Mistborn is a gateway epic with broad appeal.",
     "Absolutely. Start your free 30-day Audible trial and begin the adventure. Fans of Sanderson and high fantasy will be hooked instantly."),
  b("B01COR1GM2",
     "never-split-the-difference-voss",
     "Never Split the Difference: Negotiating as if Your Life Depended on It",
     "Chris Voss, Tahl Raz",
     "Michael Kramer",
     "https://m.media-amazon.com/images/I/51gx6VN0-UL._SL500_.jpg",
     "8h 0m",
     480,
     4.6,
     40000,
     0,
     ["business"],
     ["business","best-seller"],
     "Never Split the Difference is former FBI hostage negotiator Chris Voss's guide to high-stakes negotiation, packed with real cases and practical tactics.",
     "",
     true,
     "Never Split the Difference is former FBI hostage negotiator Chris Voss's guide to high-stakes negotiation, packed with real cases and practical tactics. Michael Kramer narrates this 8-hour audiobook.",
     "For professionals, salespeople, managers, and anyone who negotiates daily. It solves the problem of getting better outcomes by understanding that negotiation is about emotion and empathy, not just logic.",
     "Perfect for commutes; each chapter is a self-contained technique with stories, so you can apply the next tactic the same day.",
     "Voss's law-enforcement pedigree and counterintuitive techniques like tactical empathy and calibrated questions set it apart from generic negotiation advice. It is a modern classic.",
     "Absolutely. Start your free trial and put the first tactic to work today. It is one of the most immediately useful business audiobooks."),
  b("B09XRF2SWN",
     "the-housemaid-mcfadden",
     "The Housemaid",
     "Freida McFadden",
     "Lauryn Allman",
     "https://m.media-amazon.com/images/I/51evKjzP7DL._SL500_.jpg",
     "9h 0m",
     540,
     4.5,
     35000,
     0,
     ["mystery-thriller"],
     ["mystery-thriller","best-seller","top-rated"],
     "The Housemaid is Freida McFadden's twisty psychological thriller, following a live-in housemaid who uncovers dark secrets behind her employers' picture-perfect home.",
     "",
     true,
     "The Housemaid is Freida McFadden's twisty psychological thriller, following a live-in housemaid who uncovers dark secrets behind her employers' picture-perfect home. Lauryn Allman narrates this 9-hour audiobook.",
     "For fans of domestic suspense and unreliable-narrator thrillers. It solves the problem of a fast, bingeable mystery you can finish in a weekend.",
     "Great for evenings and rainy weekends; the short chapters and cliffhangers make it hard to pause.",
     "McFadden's plotting and Allman's narration maintain the tension, with a finale that recontextualizes the whole story. It is a runaway bestseller for a reason.",
     "Absolutely. Start your free trial and step inside the house. If you love domestic suspense, you will be glued to this one."),
  b("B086DL5TVZ",
     "the-thursday-murder-club-osman",
     "The Thursday Murder Club: A Novel",
     "Richard Osman",
     "Lesley Manville",
     "https://m.media-amazon.com/images/I/51r8veE8I5L._SL500_.jpg",
     "8h 0m",
     480,
     4.5,
     20000,
     0,
     ["mystery-thriller"],
     ["mystery-thriller","cozy","best-seller","series"],
     "The Thursday Murder Club is Richard Osman's best-selling cozy mystery about four friends in a retirement village who solve cold cases for fun.",
     "",
     true,
     "The Thursday Murder Club is Richard Osman's best-selling cozy mystery about four friends in a retirement village who solve cold cases for fun. Lesley Manville narrates this 8-hour audiobook.",
     "For fans of gentle, character-driven mysteries with wit and heart. It solves the problem of a charming whodunit with no gore and plenty of charm.",
     "Perfect for cozy listening — commutes, tea breaks, or a relaxed evening. A feel-good mystery that is easy to pick up.",
     "Osman's warm humor and a cast of unforgettable retirees make it stand out, and Manville's narration adds wit and warmth. It is a delightful series opener.",
     "Absolutely. Start your free trial and join the club. You will want the whole series after the first chapter."),
  b("B01D2749JA",
     "battlefield-earth-hubbard",
     "Battlefield Earth: Post-Apocalyptic Sci-Fi and New York Times Bestseller",
     "L. Ron Hubbard",
     "Josh Clark, Corey Burton, Fred Tatascorie, Stefan Rudnicki, Nancy Cartwright, R. F. Daley, Kaleo Griffith, Don Leslie, Ralph Lister, Scott Menville, Jim Meskimen, Tamra Meskimen, Phillip Proctor, Michael Yurchak, Full Cast",
     "https://m.media-amazon.com/images/I/61cbN+H7UIL._SL500_.jpg",
     "24h 0m",
     1440,
     3.8,
     15000,
     0,
     ["sci-fi","fiction"],
     ["sci-fi","long","full-cast","classic"],
     "Battlefield Earth is L. Ron Hubbard's sprawling post-apocalyptic sci-fi epic, in which humanity fights back after an alien race conquers Earth.",
     "",
     true,
     "Battlefield Earth is L. Ron Hubbard's sprawling post-apocalyptic sci-fi epic, in which humanity fights back after an alien race conquers Earth. This full-cast production runs 24 hours.",
     "For fans of classic, wide-canvas space opera and post-apocalyptic sci-fi. It solves the problem of finding a huge, immersive story that eats up hours of listening.",
     "Best for road trips and long listening stretches; at 24 hours it is excellent value per credit and a great pick for drive time.",
     "The full-cast audio production brings the epic scale to life, and its length and spectacle make it a cult favorite of long-form sci-fi fans.",
     "Absolutely. Start your free 30-day Audible trial and jump into the long, immersive saga. It is a great fit for listeners who want maximum length."),
  b("B08MVH18BX",
     "ruins-of-the-earth-hopper-chaney",
     "Ruins of the Earth: Ruins of the Earth, Book 1",
     "Christopher Hopper, J. N. Chaney",
     "R.C. Bray",
     "https://m.media-amazon.com/images/I/51WCgvhozFL._SL500_.jpg",
     "9h 0m",
     540,
     4.5,
     25000,
     0,
     ["sci-fi","fiction"],
     ["sci-fi","series"],
     "Ruins of the Earth is the first book in Christopher Hopper and J. N. Chaney's sci-fi adventure series, where a team uncovers an alien weapon beneath an ancient Earth site.",
     "",
     true,
     "Ruins of the Earth is the first book in Christopher Hopper and J. N. Chaney's sci-fi adventure series, where a team uncovers an alien weapon beneath an ancient Earth site. R.C. Bray narrates this 9-hour audiobook.",
     "For fans of military sci-fi, alien-invasion action, and ensemble casts. It solves the problem of a fast-paced thriller with big set pieces.",
     "Great for commutes and workouts; the action beats and short chapters keep momentum high.",
     "R.C. Bray's narration is a genre favorite, and Hopper and Chaney's military sci-fi chops make this a strong series entry with wide appeal.",
     "Absolutely. Start your free trial and join the mission. If you like military sci-fi with a big alien threat, this delivers."),
  b("B00I0A6HUO",
     "the-hard-thing-about-hard-things-horowitz",
     "The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers",
     "Ben Horowitz",
     "Kevin Kenerly",
     "https://m.media-amazon.com/images/I/51rQd61RAdL._SL500_.jpg",
     "9h 0m",
     540,
     4.4,
     30000,
     0,
     ["business"],
     ["business","startup"],
     "The Hard Thing About Hard Things is Ben Horowitz's candid guide to the brutal realities of building and running a startup, drawn from his own tough decisions.",
     "",
     true,
     "The Hard Thing About Hard Things is Ben Horowitz's candid guide to the brutal realities of building and running a startup, drawn from his own tough decisions. Kevin Kenerly narrates this 9-hour audiobook.",
     "For founders, executives, and startup operators navigating hard calls. It solves the problem of a no-nonsense, warts-and-all look at managing through crises.",
     "Perfect for commutes and focused sessions; the lessons map directly to real management dilemmas.",
     "Horowitz addresses the messy stuff most business books skip — layoffs, hiring, and morale — with unusual honesty. Kenerly's narration keeps it grounded.",
     "Absolutely. Start your free trial and get the straight talk. It is a must-listen for anyone leading through hard times."),
  b("B0DYGHQ7Z4",
     "nobody-knows-youre-here-greenwood",
     "Nobody Knows You're Here: A Psychological Suspense Thriller",
     "Bryn Greenwood",
     "Kristen Sieh",
     "https://m.media-amazon.com/images/I/51F7JynkXRL._SL500_.jpg",
     "8h 0m",
     480,
     4.2,
     5000,
     0,
     ["mystery-thriller"],
     ["mystery-thriller","psychological"],
     "Nobody Knows You're Here is Bryn Greenwood's psychological suspense thriller, a slow-burn story of a woman who stays hidden after a shocking act.",
     "",
     true,
     "Nobody Knows You're Here is Bryn Greenwood's psychological suspense thriller, a slow-burn story of a woman who stays hidden after a shocking act. Kristen Sieh narrates this 8-hour audiobook.",
     "For readers who love character-driven psychological suspense and morally gray protagonists. It solves the problem of a tense, atmospheric read with no easy answers.",
     "Great for quiet evenings; the building dread rewards unhurried, immersive listening.",
     "Greenwood's prose is literary and tense, and Sieh's narration captures the protagonist's isolation. It stands out for readers who want depth as well as thrills.",
     "Absolutely. Start your free trial and enter the story. It is a gripping, character-first suspense listen."),
  b("B0GRCDVC6D",
     "starship-new-jersey-box-set-bartlett",
     "Starship New Jersey Box Set: The Complete 10-Book SciFi Series",
     "Scott Bartlett",
     "Mark Boyett",
     "https://m.media-amazon.com/images/I/51kJo4UwSaL._SL500_.jpg",
     "10h 0m",
     600,
     4.3,
     10000,
     0,
     ["sci-fi","fiction"],
     ["sci-fi","series","box-set"],
     "Starship New Jersey Box Set collects the complete 10-book sci-fi series from Scott Bartlett, following the crew of a renegade military vessel through a war-torn galaxy.",
     "",
     true,
     "Starship New Jersey Box Set collects the complete 10-book sci-fi series from Scott Bartlett, following the crew of a renegade military vessel through a war-torn galaxy. Mark Boyett narrates this 10-hour audiobook.",
     "For fans of military space opera, naval-style sci-fi, and bingeable box sets. It solves the problem of getting a whole series in one credit.",
     "Great for focused listening stretches and space-opera marathons; packed episodes keep the action flowing.",
     "A full 10-book series in one box set is outstanding value, and Boyett's narration keeps the large cast of characters distinct.",
     "Absolutely. Start your free trial and board the Starship New Jersey. It is a strong pick for space-opera fans who want a lot of listening per credit.")
];

function main() {
  const data = JSON.parse(fs.readFileSync(BOOKS_PATH, "utf-8"));
  const knownAsins = new Set(data.books.map((book) => book.asin));
  const knownSlugs = new Set(data.books.map((book) => book.slug));
  let added = 0, skipped = 0;
  for (const c of NEW_BOOKS) {
    if (knownAsins.has(c.asin) || knownSlugs.has(c.slug)) { skipped++; continue; }
    data.books.push(c);
    knownAsins.add(c.asin);
    knownSlugs.add(c.slug);
    added++;
    console.log("Added: " + c.title + " (" + c.asin + ")");
  }
  fs.writeFileSync(BOOKS_PATH, JSON.stringify(data, null, 2));
  console.log("Added " + added + " books. Total: " + data.books.length + ". Skipped " + skipped + ".");
}

main();
