const fs = require("fs");
const path = require("path");

const BOOKS_PATH = path.join(__dirname, "..", "books.json");

function b(asin, slug, title, author, narrator, coverUrl, duration, durationMinutes, rating, ratingCount, listPrice, categories, tags, description, releaseDate, needsReview, q1, q2, q3, q4, q5) {
  return {
    asin, slug, title, author, narrator, coverUrl,
    duration, durationMinutes, rating, ratingCount,
    listPrice, audiblePrice: 0, isCreditEligible: true, isPlusCatalog: false,
    categories, tags, description, releaseDate,
    binding: "Audible Audiobook", formats: ["Unabridged"],
    detailPageURL: "https://www.amazon.com/dp/" + asin + "?tag=yuanyuan07-20&linkCode=ogi&th=1&psc=1",
    needsReview,
    questions: { q1, q2, q3, q4, q5 }
  };
}

const NEW_BOOKS = [
  b("B08V8877BY", "dungeon-crawler-carl-dinniman", "Dungeon Crawler Carl: A LitRPG/Gamelit Adventure", "Matt Dinniman", "Jeff Hays", "https://m.media-amazon.com/images/I/51HIZdnqASL._SL500_.jpg", "19h 30m", 1170, 4.8, 50000, 22.50, ["sci-fi", "fiction"], ["best-seller", "top-rated", "series"], "Dungeon Crawler Carl is the runaway-hit LitRPG series where Carl and his ex-girlfriend's cat are dragged into a violent, game-like alien dungeon crawl. Jeff Hays' award-winning performance makes this one of the most beloved audiobooks in the genre.", "2021-01-28", true,
    "Dungeon Crawler Carl is the first book in Matt Dinniman's wildly popular LitRPG series. Narrated by Jeff Hays, this 19.5-hour audiobook follows Carl and Princess Donut as they fight through a lethal alien dungeon with absurd humor, real stakes, and deep character growth.",
    "For fantasy and sci-fi readers who love video-game mechanics, dark humor, and surprisingly emotional storytelling. It solves the problem of finding a genuinely addictive series that keeps you laughing while still caring about the characters.",
    "Perfect for long commutes, gaming sessions, or binge-listening weekends. Each dungeon level is a natural stopping point, but the cliffhangers make it hard to pause. At nearly 20 hours, it is excellent value for one Audible credit.",
    "Most LitRPG audiobooks rely on numbers and cliches; Dungeon Crawler Carl combines clever world-building, an underdog story, and Jeff Hays' legendary multi-voice narration. It is widely considered the entry point that converted thousands of listeners to the genre.",
    "Absolutely. Start your free Audible trial, download instantly, and Carl's chaotic first dungeon level hooks you in the opening minutes. No LitRPG background is needed to enjoy it."),
  b("B09345T1HY", "carls-doomsday-scenario-dinniman", "Carl's Doomsday Scenario: Dungeon Crawler Carl, Book 2", "Matt Dinniman", "Jeff Hays", "https://m.media-amazon.com/images/I/51e1PKKdv8L._SL500_.jpg", "22h 0m", 1320, 4.8, 30000, 20.49, ["sci-fi", "fiction"], ["best-seller", "top-rated", "series"], "Book 2 of the Dungeon Crawler Carl saga escalates the chaos: new floors, new bosses, and new betrayals. Jeff Hays returns to deliver another marathon performance.", "2021-04-22", true,
    "Carl's Doomsday Scenario is the second book in the Dungeon Crawler Carl LitRPG series. The dungeon expands, the alien syndicate gets more desperate, and Carl and Princess Donut are pushed into even darker comedic chaos over 22 hours.",
    "For listeners who finished book one and want more of the series' mix of action, satire, and found-family bonds. It solves the 'what do I listen to next' problem for fans who crave a long, binge-worthy continuation.",
    "Great for commutes and marathon weekends. The escalating floors give you natural chapters, while the longer runtime makes it a strong one-credit value.",
    "Series books often sag in the middle, but Dungeon Crawler Carl keeps raising the bar with new systems, unforgettable side characters, and Hays' vocal range. Fans consistently rank book two among the best in the series.",
    "Yes. Start your free trial and pick up where book one left off; the story recaps the essentials quickly. If you loved the first book, this delivers more of everything."),
  b("B094X214V9", "dungeon-anarchists-cookbook-dinniman", "The Dungeon Anarchist's Cookbook: Dungeon Crawler Carl, Book 3", "Matt Dinniman", "Jeff Hays", "https://m.media-amazon.com/images/I/518nfG1FaYL._SL500_.jpg", "20h 30m", 1230, 4.8, 25000, 25.22, ["sci-fi", "fiction"], ["best-seller", "top-rated", "series"], "Book three raises the stakes as Carl becomes a symbol of rebellion inside the dungeon. A fan-favorite entry packed with dark humor and increasingly deadly floors.", "2021-05-14", true,
    "The Dungeon Anarchist's Cookbook is the third Dungeon Crawler Carl novel. Carl accidentally becomes the face of a dungeon-wide uprising, turning the game into a rebellion that even the alien overlords did not expect.",
    "For LitRPG and fantasy fans who want a series with momentum, humor, and genuine emotional payoff. It solves the problem of finding book three that improves on its predecessors.",
    "Excellent for longer listening sessions; the revolution arc rewards focus. At 20+ hours, one credit buys a full week of commute listening.",
    "Few series make book three their strongest, but this one expands the world, sharpens the satire, and gives Princess Donut even more spotlight. It is a high point for many listeners.",
    "Absolutely. Start your free trial, and the rebellion hook grabs you in the first chapter. Returning readers can jump straight in after a quick recap."),
  b("B09GD882BQ", "gate-of-the-feral-gods-dinniman", "The Gate of the Feral Gods: Dungeon Crawler Carl, Book 4", "Matt Dinniman", "Jeff Hays", "https://m.media-amazon.com/images/I/51rmyTTWPsL._SL500_.jpg", "22h 30m", 1350, 4.8, 20000, 26.08, ["sci-fi", "fiction"], ["best-seller", "top-rated", "series"], "Book four sends Carl and Donut into the god-level floors where the dungeon starts breaking its own rules. A wild, beloved continuation of the series.", "2021-09-16", true,
    "The Gate of the Feral Gods is book four of Dungeon Crawler Carl, taking the crawl into celestial chaos as gods and ancient powers start interfering. Narrated by Jeff Hays, it keeps the series' signature absurdity and heart.",
    "For listeners who want a series that keeps evolving instead of repeating itself. It solves the need for a long, energetic audiobook that stays funny even as the stakes get cosmic.",
    "Great for weekend binges and long road trips. The god-level floors are packed with action and comedic set pieces that reward uninterrupted listening.",
    "This entry leans into the series' biggest strength: treating absurd premises with real emotional investment. Hays' performance of new gods, monsters, and Donut's one-liners is a highlight.",
    "Yes. Start your free trial and continue the crawl. New listeners can also start here, but book one is the best introduction to the world."),
  b("B09ZJ84HC2", "butchers-masquerade-dinniman", "The Butcher's Masquerade: Dungeon Crawler Carl, Book 5", "Matt Dinniman", "Jeff Hays", "https://m.media-amazon.com/images/I/51kOQeaXbAL._SL500_.jpg", "24h 0m", 1440, 4.8, 18000, 31.62, ["sci-fi", "fiction"], ["best-seller", "top-rated", "series"], "The Butcher's Masquerade brings the dungeon crawl to a brutal carnival of gods and killers. Widely considered a peak entry in the series.", "2022-05-26", true,
    "The Butcher's Masquerade is the fifth Dungeon Crawler Carl book, centered on a deadly masquerade where the dungeon's most dangerous contestants gather. It delivers 24 hours of escalating action and emotional gut punches.",
    "For LitRPG veterans and newcomers who love ensemble casts and high-stakes spectacle. It solves the problem of finding a series that balances comedy with moments that genuinely hurt.",
    "Perfect for long listening marathons. The masquerade structure gives each character a showcase, making it ideal for focused, immersive sessions.",
    "Many fans call this the best book in the series: the stakes feel personal, the new cast members shine, and the ending lands one of the genre's most memorable punches.",
    "Absolutely. Start your free trial and let the masquerade pull you in. If you are already caught up, this is the payoff you have been waiting for."),
  b("B0CDXVN7BB", "eye-of-the-bedlam-bride-dinniman", "The Eye of the Bedlam Bride: Dungeon Crawler Carl, Book 6", "Matt Dinniman", "Jeff Hays", "https://m.media-amazon.com/images/I/51qfZAq2J4L._SL500_.jpg", "25h 0m", 1500, 4.8, 15000, 31.64, ["sci-fi", "fiction"], ["best-seller", "top-rated", "series"], "Book six of Dungeon Crawler Carl crosses into wedding-themed dungeon madness, full of traps, monsters, and the series' trademark dark comedy.", "2023-09-01", true,
    "The Eye of the Bedlam Bride is book six in the Dungeon Crawler Carl series, featuring a bizarre marriage-themed dungeon and some of the series' wildest set pieces. Jeff Hays narrates the 25-hour epic.",
    "For loyal series fans who want the crawl to keep surprising them. It solves the 'middle of the series' problem by maintaining momentum and raising the emotional stakes.",
    "Best for long listening sessions; the themed dungeon rewards full immersion. At 25 hours, one credit covers weeks of commuting.",
    "The series refuses to become predictable: the wedding-dungeon concept is absurd, yet Dinniman makes it feel earned. Hays' narration continues to be the genre benchmark.",
    "Yes. Start your free trial and continue the crawl. The recap at the start helps returning listeners jump straight in."),
  b("B0DK29VYL1", "this-inevitable-ruin-dinniman", "This Inevitable Ruin: Dungeon Crawler Carl, Book 7", "Matt Dinniman", "Jeff Hays", "https://m.media-amazon.com/images/I/51rtjss07uL._SL500_.jpg", "26h 0m", 1560, 4.8, 10000, 31.98, ["sci-fi", "fiction"], ["best-seller", "top-rated", "series"], "Book seven of Dungeon Crawler Carl pushes the crawl into its most brutal and emotional territory yet, as alliances shatter and the endgame approaches.", "2025-02-11", true,
    "This Inevitable Ruin is the seventh Dungeon Crawler Carl novel, continuing the saga as the dungeon reaches its climactic phase. It is the longest entry yet at about 26 hours.",
    "For dedicated series readers who want a satisfying, high-stakes continuation. It solves the 'long-running series fatigue' problem with fresh twists and deeper character arcs.",
    "Ideal for marathon listening; the climactic pacing makes long sessions fly by. The length delivers outstanding value per credit.",
    "Seven books in, the series still finds new ways to surprise. This entry tightens the central relationships while expanding the cosmic mythology, and Hays delivers another tour-de-force performance.",
    "Absolutely. Start your free trial, catch up with the recap, and keep going. Series readers will not want to pause."),
  b("B0FXY2JG27", "parade-of-horribles-dinniman", "A Parade of Horribles: Dungeon Crawler Carl, Book 8", "Matt Dinniman", "Jeff Hays", "https://m.media-amazon.com/images/I/51QkyISCzbL._SL500_.jpg", "27h 0m", 1620, 4.8, 5000, 31.58, ["sci-fi", "fiction"], ["best-seller", "new-release", "series"], "The latest Dungeon Crawler Carl entry raises the endgame stakes as old enemies and new horrors close in. A must-listen for series fans.", "2026-05-12", true,
    "A Parade of Horribles is the eighth book in the Dungeon Crawler Carl series, pushing the story toward its endgame with everything Carl has built on the line. It continues Jeff Hays' acclaimed narration.",
    "For listeners caught up on the series who want the next chapter immediately. It solves the wait-between-books problem for one of the most bingeable series in audiobooks.",
    "Great for long listening sessions and catch-up marathons before the finale. At 27 hours, it is exceptional value for one credit.",
    "The series' formula keeps working because Dinniman never coasts: new mechanics, new horrors, and real consequences keep the momentum. Hays' performance remains the reason many listeners choose audio first.",
    "Yes. Start your free trial and jump into the endgame. New readers should begin with book one for the full experience."),
  b("B00I3PUCIY", "red-rising-pierce-brown", "Red Rising", "Pierce Brown", "Tim Gerard Reynolds", "https://m.media-amazon.com/images/I/51IM+e-toYL._SL500_.jpg", "16h 14m", 974, 4.6, 90000, 23.60, ["sci-fi", "fiction"], ["best-seller", "classic", "series"], "Red Rising launched Pierce Brown's legendary sci-fi saga: a lowborn Red infiltrates the elite Golds to tear down a corrupt society. Tim Gerard Reynolds' narration is iconic.", "2014-01-28", true,
    "Red Rising by Pierce Brown is the first novel in the Red Rising saga, a blend of sci-fi, dystopia, and military strategy. Tim Gerard Reynolds narrates Darrow's brutal journey from Helldiver to Gold infiltrator over 16 hours.",
    "For fans of The Hunger Games, Ender's Game, and epic rebellions who want adult-level stakes. It solves the problem of finding a fast-paced sci-fi series with emotional depth and unforgettable characters.",
    "Perfect for commutes, gym sessions, or binge weekends. The academy-training structure keeps chapters short and addictive, while the finale demands uninterrupted listening.",
    "Few debuts launch a genre-defining saga this confidently. Reynolds' narration brings Darrow's rage and hope to life, making the audiobook the definitive way to experience the series.",
    "Absolutely. Start your free trial, and Darrow's first chapter hooks you immediately. It is a complete story that also sets up one of sci-fi's best trilogies."),
  b("B00R6OOUV8", "golden-son-pierce-brown", "Golden Son: Book II of the Red Rising Trilogy", "Pierce Brown", "Tim Gerard Reynolds", "https://m.media-amazon.com/images/I/514G5+-hXEL._SL500_.jpg", "17h 12m", 1032, 4.7, 60000, 26.87, ["sci-fi", "fiction"], ["best-seller", "top-rated", "series"], "Golden Son expands Red Rising into a galaxy-spanning political thriller. Betrayal, war, and impossible choices push Darrow to the edge.", "2015-01-06", true,
    "Golden Son is the second Red Rising book, expanding the revolution into space and high-stakes political warfare. Tim Gerard Reynolds returns for 17 hours of nonstop escalation.",
    "For readers who loved Red Rising and want the scale to grow. It solves the 'middle book slump' problem with one of the genre's most acclaimed second installments.",
    "Great for long sessions; the space battles and betrayals reward focus. The final act is famous for being un-put-downable.",
    "Book two takes everything from Red Rising and doubles it: more factions, more heartbreak, more jaw-dropping turns. Reynolds' performance is widely considered a masterclass in narration.",
    "Yes. Start your free trial and continue the saga. A quick recap helps returning listeners jump back in."),
  b("B074NGJ6NK", "iron-gold-pierce-brown", "Iron Gold", "Pierce Brown", "Tim Gerard Reynolds", "https://m.media-amazon.com/images/I/51oKG4sAeqL._SL500_.jpg", "22h 38m", 1358, 4.6, 40000, 31.35, ["sci-fi", "fiction"], ["best-seller", "series"], "Iron Gold launches the second Red Rising trilogy ten years after the revolution, told through four interwoven perspectives in a fragile new republic.", "2018-01-16", true,
    "Iron Gold is the fourth Red Rising book and the start of a new trilogy set a decade after the first. Its multi-perspective structure gives the shattered Republic a fuller, darker view.",
    "For Red Rising fans who want the world to keep expanding. It solves the problem of following a revolution after the war ends and idealism meets reality.",
    "Best for focused listening; four points of view reward attention. At 22+ hours, it is strong value for one credit.",
    "Adding new voices changes the tone without losing Pierce Brown's intensity. Reynolds returns for Darrow while new narrators give each perspective its own identity.",
    "Absolutely. Start your free trial, and the opening prologue reconnects you with the world. New readers should start with Red Rising."),
  b("B07JWDD9DX", "dark-age-pierce-brown", "Dark Age", "Pierce Brown", "Tim Gerard Reynolds", "https://m.media-amazon.com/images/I/51FGAP7DbxL._SL500_.jpg", "33h 47m", 2027, 4.7, 30000, 31.40, ["sci-fi", "fiction"], ["best-seller", "top-rated", "long-read", "series"], "Dark Age is the brutal fifth Red Rising book, pushing the Republic to the brink with relentless war and heartbreaking losses.", "2019-07-31", true,
    "Dark Age is the fifth Red Rising novel and one of the most intense entries in the saga. At nearly 34 hours, it throws the new Republic into total war and some of the darkest moments in the series.",
    "For dedicated sci-fi readers who want high stakes, morally gray warfare, and emotional devastation. It solves the problem of finding a long, dense audiobook that stays gripping to the end.",
    "Perfect for marathon listening; the relentless pacing makes long sessions fly. One credit buys almost 34 hours of content.",
    "Few series push their heroes this hard. Brown balances epic battle sequences with intimate character destruction, and Reynolds delivers a physically demanding performance.",
    "Yes. Start your free trial and brace yourself. This is a middle-book gauntlet that rewards committed listeners."),
  b("B0C28XJRBP", "light-bringer-pierce-brown", "Light Bringer: Red Rising, Book 6", "Pierce Brown", "Tim Gerard Reynolds", "https://m.media-amazon.com/images/I/51uxvAxiknL._SL500_.jpg", "38h 6m", 2286, 4.7, 20000, 31.64, ["sci-fi", "fiction"], ["best-seller", "top-rated", "long-read", "series"], "Light Bringer brings the second Red Rising trilogy to a stunning close, reuniting beloved characters for a final, soul-searing reckoning.", "2023-07-25", true,
    "Light Bringer is the sixth Red Rising book and the conclusion of the second trilogy. At over 38 hours, it reunites Darrow with old allies and forces him to confront what the war has made him.",
    "For long-time Red Rising readers who need a worthy continuation and emotional payoff. It solves the 'will this series land the ending' anxiety with one of the saga's best books.",
    "Made for epic listening sessions and long trips. The runtime makes it one of the highest-value single-credit listens in sci-fi.",
    "Light Bringer returns to the character-focused energy of the original trilogy while keeping the saga's scope. Reynolds' narration gives every reunion and betrayal real weight.",
    "Absolutely. Start your free trial, and the opening chapters reunite you with the cast. Readers who fell off after Iron Gold find this entry especially rewarding."),
  b("B08GB58KD5", "project-hail-mary-andy-weir", "Project Hail Mary", "Andy Weir", "Ray Porter", "https://m.media-amazon.com/images/I/51POf8gOyLL._SL500_.jpg", "16h 11m", 971, 4.8, 160000, 25.22, ["sci-fi", "fiction"], ["best-seller", "top-rated"], "Project Hail Mary is Andy Weir's blockbuster sci-fi novel about a lone astronaut racing to save Earth. Ray Porter's narration and the unforgettable Rocky make this a modern classic.", "2021-05-04", true,
    "Project Hail Mary by Andy Weir is the bestselling sci-fi adventure about an amnesiac astronaut who must save humanity from an extinction-level threat. Ray Porter narrates the 16-hour story, including one of audiobook's most beloved alien characters, Rocky.",
    "For anyone who loved The Martian or wants accessible, optimistic sci-fi with real science. It solves the problem of finding a book that is both smart and genuinely heartwarming.",
    "Perfect for commutes, road trips, or any listening moment; the mystery unfolds beautifully and the humor lands even during tense scenes.",
    "Andy Weir makes science thrilling, but what sets this audiobook apart is Rocky. Porter's performance of the alien's musical speech became an instant fan favorite, making audio the definitive format.",
    "Absolutely. Start your free trial, and the amnesia opening hooks you immediately. You will finish it in days and immediately want to recommend it."),
  b("B082BHWQCJ", "the-martian-andy-weir", "The Martian", "Andy Weir", "Wil Wheaton", "https://m.media-amazon.com/images/I/414J3xG+7+L._SL500_.jpg", "10h 53m", 653, 4.7, 90000, 20.52, ["sci-fi", "fiction"], ["best-seller", "classic"], "The Martian is the survival classic that launched Andy Weir's career: Mark Watney fights to stay alive on Mars with duct tape, potatoes, and relentless optimism.", "2020-01-01", true,
    "The Martian by Andy Weir follows astronaut Mark Watney as he survives alone on Mars after being presumed dead. Wil Wheaton narrates Watney's logbook-style adventure over nearly 11 hours.",
    "For science lovers and fans of survival stories who want humor with their tension. It solves the problem of finding a smart page-turner that works perfectly in audio.",
    "Great for commutes or lunchtime listening; the logbook chapters are short and punchy. The problem-solving structure makes it easy to pause and resume.",
    "The book inspired the hit movie, but the audiobook adds Watney's inner voice and humor. Wil Wheaton's energetic narration makes the science feel like part of an adventure.",
    "Yes. Start your free trial, and Watney's first log entry sets the tone. It is a fast, satisfying listen for any sci-fi fan."),
  b("B0721NKNHR", "artemis-andy-weir", "Artemis", "Andy Weir", "Rosario Dawson", "https://m.media-amazon.com/images/I/51fisVXQNrL._SL500_.jpg", "8h 55m", 535, 4.3, 40000, 18.70, ["sci-fi", "fiction"], ["best-seller"], "Artemis is Andy Weir's heist story set in the first city on the Moon, starring a witty smuggler with a plan that goes spectacularly wrong.", "2017-11-14", true,
    "Artemis by Andy Weir is a sci-fi heist novel set in a lunar city where a young smuggler gets caught up in a conspiracy. Rosario Dawson narrates this 9-hour caper.",
    "For fans of The Martian who want another smart, fast-paced Weir story with a different flavor. It solves the problem of wanting a shorter, punchier listen after a long epic.",
    "Great for a weekend binge or a week of commutes. The heist pacing keeps momentum high and chapters short.",
    "Weir trades survival science for a Moon-city crime caper, and Dawson brings the wisecracking protagonist to life. It is a lighter, more playful entry from a master of hard sci-fi.",
    "Absolutely. Start your free trial, and the opening setup drops you into Artemis quickly. No prior Weir knowledge needed."),
  b("B0H8T5TBBS", "infinite-extent-bobiverse-taylor", "The Infinite Extent: Bobiverse, Book 6", "Dennis E. Taylor", "Ray Porter", "https://m.media-amazon.com/images/I/51O1HmGSbEL._SL500_.jpg", "12h 0m", 720, 4.6, 2000, 19.86, ["sci-fi", "fiction"], ["series", "new-release"], "The Bobiverse returns for book six as Bob and his replicants face a new cosmic threat. Ray Porter continues his beloved narration of the self-replicating AI saga.", "2026-09-10", true,
    "The Infinite Extent is the sixth book in Dennis E. Taylor's Bobiverse series, following Bob's many replicants across the galaxy as they confront an evolving threat. Ray Porter narrates.",
    "For Bobiverse fans and sci-fi readers who love clever, character-driven space exploration. It solves the problem of waiting for the next chapter of a beloved, lighthearted epic.",
    "Excellent for commutes and relaxed evenings; the multiple-Bob perspective keeps things lively. A 12-hour runtime is a comfortable one-credit listen.",
    "Taylor's Bobiverse stands apart for its humor, hard science, and the warmth of Bob's many personalities. Porter's narration makes every Bob instantly recognizable.",
    "Yes. Start your free trial, and the recap plus new mission hook you in quickly. New listeners should begin with We Are Legion."),
  b("B099NZJJXZ", "fellowship-of-the-ring-tolkien", "The Fellowship of the Ring: Lord of the Rings, Book 1", "J. R. R. Tolkien", "Andy Serkis", "https://m.media-amazon.com/images/I/51YHc7SK5HL._SL500_.jpg", "19h 12m", 1152, 4.8, 40000, 31.62, ["fiction", "fantasy"], ["classic", "top-rated", "series"], "The definitive Lord of the Rings audiobook: Andy Serkis narrates Tolkien's masterpiece with a performance for the ages.", "2021-09-16", true,
    "The Fellowship of the Ring is the opening volume of Tolkien's Lord of the Rings, narrated by Andy Serkis. This 19-hour audiobook carries the company from the Shire to the breaking of the Fellowship.",
    "For fantasy readers who have never experienced LOTR in audio, or fans of the films who want the richer original. It solves the problem of finding a definitive, immersive classic.",
    "Perfect for long journeys and immersive listening; Tolkien's prose rewards undivided attention. Each chapter is substantial, making it ideal for evening sessions.",
    "Andy Serkis' one-man performance of every character, from Gollum to Gandalf, is widely hailed as the definitive Lord of the Rings narration. It turns a classic into a theatrical event.",
    "Absolutely. Start your free trial, and the opening chapter returns you to the Shire with fresh wonder. This is the version to own."),
  b("B07GL4J6Z1", "the-odyssey-homer-danes", "The Odyssey: Audible Iliad & Odyssey, Book 2", "Homer", "Claire Danes", "https://m.media-amazon.com/images/I/61zXf3EWpxL._SL500_.jpg", "12h 29m", 749, 4.6, 20000, 21.64, ["classics", "fiction"], ["classic", "top-rated"], "Claire Danes narrates Emily Wilson's acclaimed translation of The Odyssey, bringing Homer's epic voyage home to life.", "2018-11-20", true,
    "The Odyssey is Homer's foundational epic of Odysseus' ten-year journey home, narrated by Claire Danes in Emily Wilson's acclaimed translation. This 12.5-hour audiobook is a modern classic in audio form.",
    "For readers who want the classics made accessible and emotional, or anyone who loves myth and adventure. It solves the problem of translations that feel stiff by pairing a celebrated text with a stellar performance.",
    "Great for evening listening and slow weekends; the epic's episodes are perfect for one or two chapters per sitting.",
    "Emily Wilson's translation is the first major English version by a woman, prized for its clarity and poetry. Danes' narration makes Odysseus' longing and cunning feel immediate.",
    "Yes. Start your free trial, and the opening invocation pulls you in. You do not need any prior knowledge of Homer."),
  b("B0CJGMWVBM", "the-iliad-homer-mcdonald", "The Iliad", "Homer", "Audra McDonald", "https://m.media-amazon.com/images/I/51A8XOFIuyL._SL500_.jpg", "14h 0m", 840, 4.7, 15000, 30.02, ["classics", "fiction"], ["classic", "top-rated"], "Audra McDonald narrates Emily Wilson's verse translation of The Iliad, making the epic of rage and war soar.", "2023-09-26", true,
    "The Iliad is Homer's epic of the Trojan War and Achilles' rage, narrated by Tony-winning Audra McDonald in Emily Wilson's verse translation. This 14-hour audiobook makes the ancient epic feel new.",
    "For classicists, literature lovers, and anyone who found The Iliad intimidating in school. It solves the problem of dense translations by pairing a clear verse rendition with a transcendent performance.",
    "Perfect for reflective listening and commutes; the book's rhythm carries you. Each book of the poem is a natural chapter length.",
    "Wilson's translation is designed to be read aloud, and McDonald delivers it with operatic power. It is the rare classic that genuinely belongs in audio.",
    "Absolutely. Start your free trial, and the opening rage of Achilles lands immediately. No prior knowledge of the Trojan War is needed."),
  b("B0BXTVJK3Q", "will-of-the-many-islington", "The Will of the Many: Hierarchy, Book 1", "James Islington", "Euan Morton", "https://m.media-amazon.com/images/I/51iWZRnlRmL._SL500_.jpg", "29h 8m", 1748, 4.8, 15000, 31.64, ["fantasy", "fiction"], ["best-seller", "top-rated", "long-read", "series"], "The Will of the Many is James Islington's acclaimed fantasy epic about a hidden prince infiltrating a magical empire. Euan Morton narrates this massive opening volume.", "2023-05-23", true,
    "The Will of the Many by James Islington is the first book in the Hierarchy series, a fantasy epic of empire, magic, and hidden identity. Euan Morton narrates this 29-hour opening volume.",
    "For epic fantasy fans who loved Red Rising or The Name of the Wind and want a richly plotted new series. It solves the problem of finding a long, satisfying fantasy that rewards patience.",
    "Made for long listening sessions and multi-week commutes. At 29 hours, one credit buys an enormous, immersive story.",
    "Islington earned a reputation for airtight plotting in Licanius, and here he builds a fascinating magic system around the Roman-inspired Hierarchy. Morton's narration brings the academy and court intrigue to life.",
    "Absolutely. Start your free trial, and the protagonist's secret mission hooks you in the first chapter. This is a series worth getting in on early."),
];

const data = JSON.parse(fs.readFileSync(BOOKS_PATH, "utf-8"));
const existing = new Set(data.books.map((b) => b.asin));
let added = 0;
for (const book of NEW_BOOKS) {
  if (!existing.has(book.asin)) {
    data.books.push(book);
    existing.add(book.asin);
    added++;
    console.log("Added " + book.slug);
  } else {
    console.log("Skip existing " + book.asin);
  }
}
fs.writeFileSync(BOOKS_PATH, JSON.stringify(data, null, 2));
console.log("Batch 1 complete. Added " + added + " books. Total: " + data.books.length);
