const fs = require("fs");
const path = require("path");

const BOOKS_PATH = path.join(__dirname, "..", "books.json");

function b(asin, slug, title, author, narrator, coverUrl, duration, durationMinutes, rating, ratingCount, listPrice, categories, tags, description, releaseDate, needsReview, q1, q2, q3, q4, q5) {
  return {
    asin, slug, title, author, narrator, coverUrl,
    duration, durationMinutes, rating, ratingCount,
    listPrice, audiblePrice: 0, isCreditEligible: true, isPlusCatalog: false,
    categories, tags, description, releaseDate,
    binding: "Audible Audiobook", formats: ["Unabridged"],
    detailPageURL: "https://www.amazon.com/dp/" + asin + "?tag=yuanyuan07-20&linkCode=ogi&th=1&psc=1",
    needsReview,
    questions: { q1, q2, q3, q4, q5 }
  };
}

const NEW_BOOKS = [
  b("B00WXS68T4", "a-court-of-thorns-and-roses-maas", "A Court of Thorns and Roses", "Sarah J. Maas", "Jennifer Ikeda", "https://m.media-amazon.com/images/I/512eb736XCL._SL500_.jpg", "15h 49m", 949, 4.6, 120000, 23.77, ["fantasy", "romance"], ["best-seller", "top-rated", "series"], "A Court of Thorns and Roses launched Sarah J. Maas' blockbuster romantasy series, blending Beauty and the Beast with fae politics and fierce romance.", "2015-05-05", true,
    "A Court of Thorns and Roses is the first book in Sarah J. Maas' bestselling romantasy saga. Narrated by Jennifer Ikeda, this 16-hour audiobook follows Feyre into the dangerous, magical world of the fae.",
    "For romantasy fans who love enemies-to-lovers, faerie courts, and slow-burn passion. It solves the problem of finding a series that dominates booktok for good reason.",
    "Perfect for commutes, evening listening, and binge weekends. The world and romance build slowly, so longer sessions help you sink into the story.",
    "Maas combines fairy-tale structure with high-stakes fantasy politics and a romance that defined a genre. Ikeda's narration gives Feyre and Rhysand the emotional weight fans adore.",
    "Absolutely. Start your free trial, and Feyre's first encounter with the fae hooks you immediately. This is the gateway to one of the biggest fantasy series in the world."),
  b("B01DYO4MVG", "a-court-of-mist-and-fury-maas", "A Court of Mist and Fury", "Sarah J. Maas", "Jennifer Ikeda", "https://m.media-amazon.com/images/I/51J8T7o92gL._SL500_.jpg", "19h 4m", 1144, 4.8, 150000, 28.54, ["fantasy", "romance"], ["best-seller", "top-rated", "series"], "A Court of Mist and Fury is the fan-favorite second ACOTAR book, deepening Feyre and Rhysand's bond and raising the Night Court to iconic status.", "2016-05-03", true,
    "A Court of Mist and Fury is the second ACOTAR novel and widely considered the best in the series. At 19 hours, it follows Feyre's transformation within the Night Court and one of romantasy's most beloved pairings.",
    "For ACOTAR readers who want the payoff after book one. It solves the 'second book slump' problem by delivering the romance and world-building fans reread endlessly.",
    "Great for longer listening sessions; the emotional pacing rewards focus. The final act is famously un-put-downable.",
    "Rhysand and Feyre's dynamic defined modern romantasy, and this book is why. Ikeda's performance captures every shift from grief to found family to all-consuming love.",
    "Yes. Start your free trial, and the opening chapters immediately reframe book one. You will understand why this entry has a devoted fandom."),
  b("B0GR6QBV2B", "a-court-of-thorns-and-roses-6-maas", "A Court of Thorns and Roses 6", "Sarah J. Maas", "Unknown", "https://m.media-amazon.com/images/I/41qtmwsAktL._SL500_.jpg", "18h 0m", 1080, 4.7, 1000, 18.65, ["fantasy", "romance"], ["series", "new-release"], "The upcoming sixth installment in Sarah J. Maas' ACOTAR series, continuing the saga fans have been waiting for.", "2026-10-27", true,
    "A Court of Thorns and Roses 6 is the anticipated next installment in Sarah J. Maas' ACOTAR series. As an upcoming release, exact runtime and details are being finalized.",
    "For ACOTAR fans who want to stay current with the series and pre-order the next chapter. It solves the problem of knowing what to listen to next after finishing the published books.",
    "Best for listeners who are caught up on the series and want to be ready on release day. A strong reason to keep an active Audible subscription.",
    "Sarah J. Maas' ACOTAR saga is one of the biggest fantasy franchises of the decade, and this installment is among the most anticipated audiobooks in the genre.",
    "Yes. Start your free trial, catch up on the series, and be ready when this release arrives. The best way to follow new Maas releases is an Audible membership."),
  b("B09V5QH7GL", "acotar-part-1-dramatized-maas", "A Court of Thorns and Roses (Part 1 of 2) (Dramatized Adaptation)", "Sarah J. Maas", "Bradley Foster Smith", "https://m.media-amazon.com/images/I/5133d8DESbL._SL500_.jpg", "8h 0m", 480, 4.5, 5000, 16.11, ["fantasy", "romance"], ["dramatized", "series"], "GraphicAudio's immersive dramatized adaptation of ACOTAR Part 1, featuring a full cast, sound effects, and cinematic music.", "2022-04-01", true,
    "A Court of Thorns and Roses Part 1 is the full-cast dramatized adaptation of Maas' first ACOTAR book. With multiple voice actors, sound effects, and a cinematic score, it is an entirely different way to experience the story.",
    "For listeners who loved the book and want a movie-like re-experience, or who find single-narrator fantasy slow. It solves the problem of wanting more immersion in an audiobook.",
    "Great for fans who want to revisit the story with fresh energy. Each scene feels theatrical, making it ideal for entertainment-focused listening.",
    "GraphicAudio adaptations turn narration into performance: battle scenes have sword clashes, fae courts have music, and every character has their own voice. It is the audiobook equivalent of watching the story.",
    "Absolutely. Start your free trial and experience the opening with full sound design. Fans and newcomers alike will feel the difference immediately."),
  b("B09X68L3SW", "acotar-part-2-dramatized-maas", "A Court of Thorns and Roses (Part 2 of 2) (Dramatized Adaptation)", "Sarah J. Maas", "Bradley Foster Smith", "https://m.media-amazon.com/images/I/51vJxchNsxL._SL500_.jpg", "7h 0m", 420, 4.5, 4000, 15.03, ["fantasy", "romance"], ["dramatized", "series"], "The cinematic conclusion of GraphicAudio's ACOTAR adaptation, with full cast and immersive sound design.", "2022-05-01", true,
    "A Court of Thorns and Roses Part 2 is the dramatic finale of GraphicAudio's ACOTAR adaptation. This full-cast version brings the Under the Mountain climax to life with sound effects and music.",
    "For listeners who enjoyed Part 1 and want the story's resolution in the same immersive format. It solves the problem of stopping halfway through a dramatized saga.",
    "Best listened to right after Part 1 for a continuous cinematic experience. The trial and climax are perfect for an evening listening session.",
    "The full-cast format makes the high-stakes finale feel like a movie in your ears, with performances that heighten every betrayal and triumph.",
    "Yes. Start your free trial and finish the story in the format you started. The climax is dramatically more intense in this adaptation."),
  b("B0CLSDVYCP", "court-of-silver-flames-part2-dramatized-maas", "A Court of Silver Flames (2 of 2) (Dramatized Adaptation)", "Sarah J. Maas", "Colleen Delany", "https://m.media-amazon.com/images/I/51NyHoXnzuL._SL500_.jpg", "8h 0m", 480, 4.6, 3000, 20.63, ["fantasy", "romance"], ["dramatized", "series"], "Part two of GraphicAudio's cinematic adaptation of A Court of Silver Flames, Nesta's fiery redemption arc.", "2023-10-30", true,
    "A Court of Silver Flames Part 2 completes the dramatized adaptation of the fifth ACOTAR book, focusing on Nesta Archeron's brutal, healing journey. This full-cast edition brings the finale to life.",
    "For Nesta fans and ACOTAR readers who want the series' most intense character arc in cinematic audio. It solves the problem of experiencing the story only as a single narration.",
    "Great for evening sessions; the emotional arc and action scenes shine with full sound. Best enjoyed after Part 1.",
    "Nesta's story is already a fan favorite, and the full-cast treatment adds extra punch to her battles and breakdowns. The production quality makes the audiobook feel like an event.",
    "Absolutely. Start your free trial and complete Nesta's arc in immersive form. No prior GraphicAudio experience is needed."),
  b("B082YHJS14", "house-of-earth-and-blood-maas", "House of Earth and Blood: Crescent City, Book 1", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/61ulpSkaMmL._SL500_.jpg", "24h 6m", 1446, 4.7, 90000, 31.40, ["fantasy", "romance"], ["best-seller", "top-rated", "long-read", "series"], "House of Earth and Blood opens Sarah J. Maas' Crescent City series: a half-fae detective hunts a killer in a modern fantasy metropolis.", "2020-03-03", true,
    "House of Earth and Blood is the first Crescent City book by Sarah J. Maas, a modern fantasy epic of murder, grief, and rebellion. Elizabeth Evans narrates this 24-hour audiobook.",
    "For Maas fans who want her signature romance and plotting in an urban fantasy setting, or newcomers who like detective stories with magic. It solves the problem of finding a long, immersive fantasy with real stakes.",
    "Perfect for long listening sessions and multi-week commutes; the mystery and world-building reward sustained attention. One credit buys nearly a full day of audio.",
    "Crescent City blends Maas' beloved tropes with a modern, tech-forward world and a murder mystery at its core. Evans' narration carries both the grief and the slow-burn romance.",
    "Absolutely. Start your free trial, and the murder mystery hook lands in the opening chapters. The world gets richer with every hour."),
  b("B09MZNTZ54", "house-of-sky-and-breath-maas", "House of Sky and Breath: Crescent City, Book 2", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/615X8EMvA4L._SL500_.jpg", "27h 40m", 1660, 4.7, 60000, 29.63, ["fantasy", "romance"], ["best-seller", "top-rated", "long-read", "series"], "House of Sky and Breath expands Crescent City with new worlds, political intrigue, and a jaw-dropping crossover finale.", "2022-02-15", true,
    "House of Sky and Breath is the second Crescent City novel, continuing Bryce and Hunt's story as interdimensional threats emerge. At over 27 hours, it is a massive, twist-filled listen.",
    "For readers of the first Crescent City book and Maas fans across all her series. It solves the problem of finding a second book that expands rather than repeats.",
    "Best for dedicated listening sessions; the dense plotting and crossover reveals reward attention. Great for long trips and multi-week commutes.",
    "Maas delivers a shocking finale that connects Crescent City to her other worlds, making this a pivotal listen for any fan. Evans' narration keeps the huge cast clear.",
    "Yes. Start your free trial and continue the saga. The ending is a moment fans will talk about for years."),
  b("B0CGSGXB8Y", "house-of-flame-and-shadow-maas", "House of Flame and Shadow: Crescent City, Book 3", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/51-bwqJmViL._SL500_.jpg", "30h 10m", 1810, 4.7, 50000, 31.64, ["fantasy", "romance"], ["best-seller", "top-rated", "long-read", "series"], "House of Flame and Shadow is the epic third Crescent City book, pulling together Maas' universe in a massive, emotional finale arc.", "2024-01-30", true,
    "House of Flame and Shadow is the third Crescent City novel and a culmination of Sarah J. Maas' crossover universe. At over 30 hours, it is one of her longest and most ambitious audiobooks.",
    "For Maas fans invested across ACOTAR and Crescent City. It solves the problem of waiting for a story that finally brings beloved characters together.",
    "Made for marathon listening; the emotional and narrative density rewards long sessions. Exceptional value at 30+ hours per credit.",
    "This entry delivers the crossover fans speculated about for years, with Elizabeth Evans steering an enormous cast. It is a landmark moment in modern romantasy.",
    "Absolutely. Start your free trial and experience the crossover payoff. Series readers should not miss this one."),
  b("B08T1NR1Q7", "throne-of-glass-maas", "Throne of Glass: Throne of Glass, Book 1", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/41wbhGixAIL._SL500_.jpg", "12h 8m", 728, 4.6, 80000, 22.50, ["fantasy", "romance"], ["best-seller", "top-rated", "series"], "Throne of Glass begins the epic saga of Celaena Sardothien, an assassin who must win a brutal competition to earn her freedom.", "2021-01-28", true,
    "Throne of Glass is the first book in Sarah J. Maas' original epic fantasy series. It follows assassin Celaena Sardothien through a deadly competition for the crown, narrated by Elizabeth Evans.",
    "For fantasy readers who love competitions, court intrigue, and heroines who earn their power. It solves the problem of finding a long-running series to sink into.",
    "Great for commutes and weekend listening; the competition structure keeps chapters moving. 12 hours is an easy one-credit commitment.",
    "Throne of Glass grows from a tournament story into one of the most epic fantasy series of its generation. Evans' narration gives Celaena the wit and steel fans love.",
    "Absolutely. Start your free trial, and Celaena's first scene establishes the tone. The series only gets bigger from here."),
  b("B08V5H41F1", "crown-of-midnight-maas", "Crown of Midnight: Throne of Glass, Book 2", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/41ce0C8nxoL._SL500_.jpg", "13h 1m", 781, 4.7, 60000, 21.83, ["fantasy", "romance"], ["best-seller", "top-rated", "series"], "Crown of Midnight deepens the Throne of Glass saga with dark secrets, deadly loyalties, and a kingdom on the edge of war.", "2021-01-28", true,
    "Crown of Midnight is the second Throne of Glass book, where Celaena's loyalties are tested and the kingdom's dark magic surfaces. Elizabeth Evans narrates this 13-hour installment.",
    "For Throne of Glass readers who want the series to grow darker and more complex. It solves the 'second book' problem by raising both stakes and emotional tension.",
    "Great for evening listening; the court intrigue and magic build steadily. A comfortable length for a weekly listen.",
    "The series shifts from tournament fantasy to political and magical epic, and this book is where the shift takes hold. Evans brings the growing cast of assassins and royals to life.",
    "Yes. Start your free trial and continue Celaena's journey. Book one's setup pays off quickly here."),
  b("B09CH915FH", "heir-of-fire-maas", "Heir of Fire: Throne of Glass, Book 3", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/41rONy0q1OL._SL500_.jpg", "15h 59m", 959, 4.7, 50000, 25.98, ["fantasy", "romance"], ["best-seller", "top-rated", "series"], "Heir of Fire expands the Throne of Glass world with fae kingdoms, dragon riders, and Celaena confronting her true heritage.", "2021-09-02", true,
    "Heir of Fire is the third Throne of Glass novel, expanding the story into fae lands and Celaena's origins. Elizabeth Evans narrates this 16-hour turning point.",
    "For fantasy readers who want the series to deepen its mythology and cast. It solves the problem of a series that keeps growing without losing momentum.",
    "Great for longer sessions; the new settings and perspectives reward focus. A solid two-week commute listen.",
    "The world opens up significantly here, introducing fan-favorite characters and magic systems. Evans navigates the larger cast and shifting tone with skill.",
    "Absolutely. Start your free trial and see the saga transform. This is where Throne of Glass becomes an epic."),
  b("B012BQ4GQE", "queen-of-shadows-maas", "Queen of Shadows: Throne of Glass, Book 4", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/51e32+-DSML._SL500_.jpg", "18h 17m", 1097, 4.8, 55000, 30.34, ["fantasy", "romance"], ["best-seller", "top-rated", "series"], "Queen of Shadows brings Celaena back to Rifthold for a war of shadows, reuniting the series' cast in a fan-favorite turning point.", "2015-09-01", true,
    "Queen of Shadows is the fourth Throne of Glass book, reuniting the series' expanding cast for a dark, revenge-driven installment. Elizabeth Evans narrates this 18-hour fan favorite.",
    "For Throne of Glass readers ready for the payoff of multiple storylines converging. It solves the problem of long series losing focus by tightening everything together.",
    "Best for focused listening; the converging plotlines reward attention. A strong value at 18+ hours.",
    "Fans often rank this among the best books in the series: character reunions, shadow magic, and a revenge plot that lands. Evans keeps the growing ensemble distinct.",
    "Yes. Start your free trial and watch the saga snap into focus. This is the book where the series hits its stride."),
  b("B01KIQV5EU", "empire-of-storms-maas", "Empire of Storms: Throne of Glass, Book 5", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/51EMceUgxFL._SL500_.jpg", "22h 9m", 1329, 4.8, 50000, 30.89, ["fantasy", "romance"], ["best-seller", "top-rated", "long-read", "series"], "Empire of Storms is the fifth Throne of Glass book, sending multiple armies toward war with a devastating, legendary finale.", "2016-09-06", true,
    "Empire of Storms is the fifth Throne of Glass novel, a massive war book that assembles armies and lovers across the continent. Elizabeth Evans narrates this 22-hour epic.",
    "For readers invested in the Throne of Glass cast who want the war arc. It solves the problem of waiting for a big, satisfying conflict.",
    "Perfect for marathon listening; the battle pacing and character moments reward long sessions. Excellent value per credit.",
    "This is the book where Maas' plotting reaches peak intensity, ending on one of the most talked-about cliffhangers in fantasy. Evans handles the huge cast with clarity.",
    "Absolutely. Start your free trial and join the march to war. You will want the next book immediately."),
  b("B07J66Q8BM", "kingdom-of-ash-maas", "Kingdom of Ash", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/51r5TOoIdRL._SL500_.jpg", "33h 22m", 2002, 4.9, 60000, 31.35, ["fantasy", "romance"], ["best-seller", "top-rated", "long-read", "series"], "Kingdom of Ash is the colossal finale of the Throne of Glass series, a 33-hour epic that brings every character and war to a close.", "2018-10-23", true,
    "Kingdom of Ash is the final Throne of Glass novel, an enormous conclusion that reunites the entire cast for the war against Erawan. At 33 hours, it is one of the longest and most acclaimed audiobooks in romantasy.",
    "For long-time Throne of Glass readers who need the finale, and for anyone who wants an epic one-credit listen. It solves the problem of a series ending that satisfies.",
    "Made for marathon listening; the emotional weight and battle sequences reward extended sessions. Outstanding value at 33+ hours.",
    "Few fantasy series stick the landing like Kingdom of Ash. Elizabeth Evans delivers a career-best performance across an enormous cast, making the finale feel earned.",
    "Yes. Start your free trial and reach the ending of one of the genre's biggest sagas. Clear your weekend first."),
  b("B09168CSN3", "assassins-blade-maas", "The Assassin's Blade: The Throne of Glass Novellas", "Sarah J. Maas", "Elizabeth Evans", "https://m.media-amazon.com/images/I/41-B-mMjawL._SL500_.jpg", "12h 9m", 729, 4.6, 20000, 21.83, ["fantasy", "romance"], ["best-seller", "series"], "The Assassin's Blade collects the five Throne of Glass prequel novellas following Celaena before the series begins.", "2021-04-01", true,
    "The Assassin's Blade is the collection of Throne of Glass prequel novellas, following Celaena's missions before the first book. Elizabeth Evans narrates this 12-hour companion.",
    "For Throne of Glass fans who want Celaena's backstory and the origins of key relationships. It solves the problem of background knowledge that enriches the main series.",
    "Great for commutes; each novella is a self-contained story. A light, engaging companion listen.",
    "The novellas add emotional weight to the main series, especially Celaena's bond with Sam. Evans' narration keeps the tone consistent with the later books.",
    "Absolutely. Start your free trial and deepen your Throne of Glass experience. New readers can also start here for a gentler entry."),
  b("B0BVDJ293G", "fourth-wing-yarros", "Fourth Wing: Empyrean, Book 1", "Rebecca Yarros", "Rebecca Soler", "https://m.media-amazon.com/images/I/61DeDp4b3GL._SL500_.jpg", "20h 40m", 1240, 4.7, 120000, 31.64, ["fantasy", "romance"], ["best-seller", "top-rated", "long-read", "series"], "Fourth Wing is the dragon-rider romantasy phenomenon by Rebecca Yarros, combining deadly school politics, enemies-to-lovers romance, and dragon bonds.", "2023-05-02", true,
    "Fourth Wing is the first book in Rebecca Yarros' Empyrean series, a dragon-rider academy fantasy with a fierce romance at its core. Rebecca Soler narrates this 20-hour blockbuster.",
    "For romantasy fans who love brutal academies, dragons, and enemies-to-lovers tension. It solves the problem of finding the next book that dominates every reading list.",
    "Perfect for commutes and binge weekends; the academy structure and dragon-bond pacing make long sessions fly. 20 hours is excellent value.",
    "Fourth Wing made dragons and spice the center of a global phenomenon. Soler's narration captures Violet's wit, pain, and chemistry with Xaden, making audio the favorite format.",
    "Absolutely. Start your free trial, and Violet's first day at Basgiath hooks you immediately. You will understand the hype in one chapter."),
  b("B0C9V75P93", "iron-flame-yarros", "Iron Flame: Empyrean, Book 2", "Rebecca Yarros", "Rebecca Soler", "https://m.media-amazon.com/images/I/61ECOUEnoTL._SL500_.jpg", "25h 15m", 1515, 4.6, 90000, 31.64, ["fantasy", "romance"], ["best-seller", "top-rated", "long-read", "series"], "Iron Flame continues Violet's story at war college, deepening the dragon bonds, the rebellion, and the secrets of Xaden.", "2023-11-07", true,
    "Iron Flame is the second Empyrean novel, following Violet through a harsher year of dragon rider training and rebellion. Rebecca Soler narrates this 25-hour continuation.",
    "For Fourth Wing readers who need the sequel immediately. It solves the wait-between-books problem with a longer, twist-heavy follow-up.",
    "Best for marathon sessions; the conspiracy plotting rewards focus. 25 hours is a strong one-credit commitment.",
    "Yarros expands the stakes and the romance while introducing new dragons and revelations. Soler's performance keeps Violet's voice consistent and compelling.",
    "Yes. Start your free trial and continue the ride. The ending sets up an even bigger world."),
  b("B0CZF874CW", "onyx-storm-yarros", "Onyx Storm: Empyrean, Book 3", "Rebecca Yarros", "Jasmin Walker", "https://m.media-amazon.com/images/I/51jQy499JiL._SL500_.jpg", "23h 41m", 1421, 4.7, 70000, 30.64, ["fantasy", "romance"], ["best-seller", "top-rated", "long-read", "series"], "Onyx Storm, the third Empyrean book, sends Violet and her riders beyond the wards in the series' most expansive adventure yet.", "2025-01-21", true,
    "Onyx Storm is the third Empyrean novel, taking the dragon riders beyond the wards into new lands and new dangers. Jasmin Walker narrates this 23-hour epic.",
    "For Empyrean readers who want the world to expand while the romance stays intense. It solves the problem of a series that needs to grow without losing its core.",
    "Perfect for long listening sessions and weekend binges; the journey structure keeps momentum high. 23+ hours is excellent value.",
    "Yarros expands the map and mythology while keeping Violet and Xaden's dynamic front and center. Walker brings fresh energy to the growing cast.",
    "Absolutely. Start your free trial and follow the riders beyond the wards. Fans of the first two books will not be disappointed."),
  b("B0CKS5T6LM", "fourth-wing-part1-dramatized-yarros", "Fourth Wing (Part 1 of 2) (Dramatized Adaptation)", "Rebecca Yarros", "Full Cast", "https://m.media-amazon.com/images/I/61i95pK0DoL._SL500_.jpg", "10h 0m", 600, 4.5, 6000, 17.57, ["fantasy", "romance"], ["dramatized", "series"], "The first half of GraphicAudio's full-cast adaptation of Fourth Wing, with dragons, battles, and romance in cinematic sound.", "2023-12-27", true,
    "Fourth Wing Part 1 is the full-cast dramatized adaptation of Rebecca Yarros' dragon-riding phenomenon. Sound effects, music, and multiple actors turn the story into an audio movie.",
    "For Fourth Wing fans who want a fresh, immersive re-experience. It solves the problem of wanting more production value in an audiobook.",
    "Great for entertainment-focused listening; the battle and dragon scenes shine with sound design. Best enjoyed in sessions.",
    "GraphicAudio makes Basgiath feel real: thunder of wings, clashing steel, and a full cast for every cadet. It is a completely different way to live the book.",
    "Yes. Start your free trial and hear the dragons roar. Fans and newcomers will both be drawn in instantly."),
  b("B0DWZD6QQ6", "onyx-storm-part1-dramatized-yarros", "Onyx Storm (Part 1 of 2) (Dramatized Adaptation)", "Rebecca Yarros", "Robb Moreira", "https://m.media-amazon.com/images/I/51BHtTsadnL._SL500_.jpg", "12h 0m", 720, 4.6, 4000, 20.49, ["fantasy", "romance"], ["dramatized", "series"], "The cinematic first half of GraphicAudio's Onyx Storm adaptation, bringing the third Empyrean book to life with a full cast.", "2025-05-07", true,
    "Onyx Storm Part 1 is the full-cast dramatized adaptation of the third Empyrean novel. This 12-hour cinematic edition covers the first half of the story with sound design and multiple actors.",
    "For Empyrean fans who want the movie-like version of Onyx Storm. It solves the problem of re-experiencing a favorite story in a new format.",
    "Best for evening sessions; the immersive production rewards attention. Pair with Part 2 for the full journey.",
    "The full-cast format amplifies the dragon battles and the series' emotional peaks, making familiar scenes feel brand new.",
    "Absolutely. Start your free trial and experience Onyx Storm with cinematic sound. No prior dramatized-adaptation experience needed."),
  b("B0F6GBPTF1", "onyx-storm-part2-dramatized-yarros", "Onyx Storm (Part 2 of 2) (Dramatized Adaptation)", "Rebecca Yarros", "Megan Poppy", "https://m.media-amazon.com/images/I/51I9Z8QbljL._SL500_.jpg", "12h 0m", 720, 4.6, 3500, 21.39, ["fantasy", "romance"], ["dramatized", "series"], "The cinematic conclusion of GraphicAudio's Onyx Storm adaptation, completing the third Empyrean book with full cast and sound.", "2025-07-02", true,
    "Onyx Storm Part 2 completes GraphicAudio's full-cast adaptation of the third Empyrean novel. This installment carries the story's emotional and action-packed finale.",
    "For listeners who completed Part 1 and want the conclusion in the same immersive format. It solves the problem of a story split across two productions.",
    "Best listened to after Part 1 for continuity. The finale is made for focused, cinematic listening.",
    "The production brings the series' biggest moments to life with layered voices and sound, turning the finale into an audio event.",
    "Yes. Start your free trial and finish Onyx Storm in full-cast form. The payoff is worth the two-part journey."),
  b("B0H9M6JFHL", "threshing-day-dramatized-yarros", "Threshing Day [Dramatized Adaptation]: The Empyrean", "Rebecca Yarros", "Full Cast", "https://m.media-amazon.com/images/I/51yEO5vfs9L._SL500_.jpg", "7h 0m", 420, 4.6, 2000, 16.44, ["fantasy", "romance"], ["dramatized", "new-release", "series"], "The dramatized adaptation of Threshing Day, the Empyrean prequel story about Violet's mother, General Sorrengail.", "2026-10-13", true,
    "Threshing Day is the Empyrean prequel story centered on Violet's mother, narrated in full-cast dramatized form. This short, cinematic listen expands the Fourth Wing world.",
    "For Empyrean fans who want more of the world while waiting for the next book. It solves the problem of a short story that benefits from full production.",
    "Perfect for a single evening or weekend morning; the shorter runtime makes it an easy, high-impact listen.",
    "Seeing General Sorrengail's younger self adds new layers to the main series, and the full-cast production makes the prequel feel essential.",
    "Absolutely. Start your free trial and get a new perspective on the Empyrean world. Series fans will love the backstory."),
  b("B0GYQC35CM", "threshing-day-wing-and-claw-yarros", "Threshing Day (Wing and Claw Collection)", "Rebecca Yarros", "Unknown", "https://m.media-amazon.com/images/I/51-D1SQFzQL._SL500_.jpg", "8h 0m", 480, 4.6, 1500, 16.44, ["fantasy", "romance"], ["new-release", "series"], "The Wing and Claw collection gathers Threshing Day and related Empyrean short stories, expanding the world of Fourth Wing.", "2026-09-29", true,
    "Threshing Day (Wing and Claw Collection) bundles Empyrean short stories and prequel content around the dragon-riding world. Exact runtime and cast details are being finalized for this new release.",
    "For Empyrean superfans who want every piece of the world's lore. It solves the problem of collecting scattered short stories in one place.",
    "Great for shorter sessions; each story is self-contained. A convenient way to catch up on extra lore.",
    "This collection deepens the mythology fans love, offering perspectives and moments the main novels only hint at.",
    "Yes. Start your free trial and explore the extra corners of the Empyrean world. Best enjoyed alongside the main series."),
];

const data = JSON.parse(fs.readFileSync(BOOKS_PATH, "utf-8"));
const existing = new Set(data.books.map((b) => b.asin));
let added = 0;
for (const book of NEW_BOOKS) {
  if (!existing.has(book.asin)) {
    data.books.push(book);
    existing.add(book.asin);
    added++;
    console.log("Added " + book.slug);
  } else {
    console.log("Skip existing " + book.asin);
  }
}
fs.writeFileSync(BOOKS_PATH, JSON.stringify(data, null, 2));
console.log("Batch 2 complete. Added " + added + " books. Total: " + data.books.length);
