const fs = require("fs");
const path = require("path");

const BOOKS_PATH = path.join(__dirname, "..", "books.json");

function b(asin, slug, title, author, narrator, coverUrl, duration, durationMinutes, rating, ratingCount, listPrice, categories, tags, description, releaseDate, needsReview, q1, q2, q3, q4, q5) {
  return {
    asin, slug, title, author, narrator, coverUrl,
    duration, durationMinutes, rating, ratingCount,
    listPrice, audiblePrice: 0, isCreditEligible: true, isPlusCatalog: false,
    categories, tags, description, releaseDate,
    binding: "Audible Audiobook", formats: ["Unabridged"],
    detailPageURL: "https://www.amazon.com/dp/" + asin + "?tag=yuanyuan07-20&linkCode=ogi&th=1&psc=1",
    needsReview,
    questions: { q1, q2, q3, q4, q5 }
  };
}

const NEW_BOOKS = [
  b("B0FTB8MDVN", "the-calamity-club-stockett", "The Calamity Club: A Novel", "Kathryn Stockett", "Jenna Lamia", "https://m.media-amazon.com/images/I/515yERTsV8L._SL500_.jpg", "14h 0m", 840, 4.5, 5000, 31.58, ["fiction"], ["new-release", "best-seller"], "The Calamity Club is Kathryn Stockett's long-awaited new novel, a witty, character-rich story of friendship and reinvention.", "2026-05-05", true,
    "The Calamity Club is Kathryn Stockett's 2026 novel, her first since The Help. Narrated by Jenna Lamia, this 14-hour story follows a group of women whose club becomes a place of secrets and second chances.",
    "For readers of literary fiction and book-club favorites who loved The Help. It solves the problem of finding a warm, ensemble-driven novel from a beloved author.",
    "Great for commutes and weekend sessions; the ensemble structure rewards steady listening. A comfortable two-week listen.",
    "Stockett is a master of group dynamics and Southern storytelling, and Lamia's narration gives each club member a distinct voice. It is a must-listen for book clubs.",
    "Absolutely. Start your free trial, and the first club meeting introduces the cast with wit and warmth. You will be invested by the end of chapter one."),
  b("B0FTT8BQ7C", "theo-of-golden-allen-levi", "Theo of Golden: A Novel", "Allen Levi", "David Morse", "https://m.media-amazon.com/images/I/41Ae9ByqjqL._SL500_.jpg", "8h 0m", 480, 4.5, 3000, 22.49, ["fiction"], ["new-release"], "Theo of Golden is an intimate, lyrical novel about a young man discovering love, music, and his own voice in a small mountain town.", "2025-12-02", true,
    "Theo of Golden by Allen Levi is a 2025 literary novel about a thoughtful young man navigating music, love, and self-discovery in a small town. David Morse narrates this 8-hour story.",
    "For readers who love quiet, character-driven fiction with musical soul. It solves the problem of finding a gentle, beautifully written listen to slow down with.",
    "Perfect for calm evenings and reflective commutes; the lyrical tone rewards unhurried listening. A manageable one-week commitment.",
    "Levi is a songwriter, and it shows: the prose has rhythm and warmth. Morse's narration matches the novel's contemplative, tender mood.",
    "Absolutely. Start your free trial and step into Theo's world. Literary-fiction readers will be quietly moved."),
  b("B0FKTTYMVG", "yesteryear-burke", "Yesteryear: A GMA Book Club Pick: A Novel", "Caro Claire Burke", "Rebecca Lowman", "https://m.media-amazon.com/images/I/41uMaiWfXEL._SL500_.jpg", "11h 0m", 660, 4.5, 4000, 23.40, ["fiction"], ["new-release", "book-club"], "Yesteryear is a GMA Book Club pick about a woman who returns to her hometown and confronts the summer that changed everything.", "2026-04-07", true,
    "Yesteryear by Caro Claire Burke is a 2026 GMA Book Club pick about returning home and confronting the past. Rebecca Lowman narrates this 11-hour literary novel.",
    "For readers who love small-town secrets, coming-of-age reflection, and women's fiction. It solves the problem of finding a rich book-club discussion listen.",
    "Great for evenings and weekends; the layered timeline rewards steady listening. A solid two-week read.",
    "Burke weaves past and present with emotional precision, and Lowman's narration keeps both timelines distinct. It is a thoughtful, resonant pick.",
    "Absolutely. Start your free trial and travel back to Yesteryear. Book clubs will find plenty to discuss."),
  b("B0F9MJ1XQ6", "mad-mabel-hepworth", "Mad Mabel: A Novel", "Sally Hepworth", "Hannah Fredericksen", "https://m.media-amazon.com/images/I/41e7rwJLpUL._SL500_.jpg", "9h 0m", 540, 4.4, 5000, 20.24, ["mystery-thriller"], ["new-release"], "Mad Mabel is Sally Hepworth's twisty domestic thriller about the neighbor everyone talks about and the secrets she is hiding.", "2026-04-21", true,
    "Mad Mabel by Sally Hepworth is a 2026 domestic thriller centered on a neighborhood's most talked-about resident. Hannah Fredericksen narrates this 9-hour listen.",
    "For fans of domestic suspense and neighborhood-secrets stories. It solves the problem of finding a sharp, fast-paced thriller from a reliable author.",
    "Great for commutes and evenings; the shifting perspectives keep momentum high. A fast weekend listen.",
    "Hepworth is known for turning ordinary settings sinister, and Mad Mabel delivers layered character reveals. Fredericksen's narration keeps the ambiguity alive.",
    "Absolutely. Start your free trial and meet the neighbors. Thriller fans will be hooked quickly."),
  b("B0FWG871V8", "whistler-ann-patchett", "Whistler: A Novel", "Ann Patchett", "Ann Patchett", "https://m.media-amazon.com/images/I/419PAU-R+YL._SL500_.jpg", "12h 0m", 720, 4.5, 4000, 26.09, ["fiction"], ["new-release", "best-seller"], "Whistler is Ann Patchett's new novel about art, obsession, and the people who make beautiful things at great cost.", "2026-06-02", true,
    "Whistler by Ann Patchett is a 2026 literary novel exploring art, ambition, and the moral costs of beauty. Patchett narrates her own work in this 12-hour audiobook.",
    "For literary-fiction readers who love Patchett's luminous prose and character depth. It solves the problem of finding a serious, rewarding novel from one of America's best writers.",
    "Best for unhurried evenings and weekends; the prose rewards attentive listening. A rich two-week read.",
    "Patchett's own narration adds intimacy to her sentences, and the novel's exploration of the art world is both elegant and unsettling. It is a major new release.",
    "Absolutely. Start your free trial and let Patchett's voice carry you into the story. Literary readers will savor every chapter."),
  b("B0F14PDX2Z", "harry-potter-sorcerers-stone-full-cast", "Harry Potter and the Sorcerer's Stone (Full-Cast Edition)", "J.K. Rowling", "Hugh Laurie", "https://m.media-amazon.com/images/I/51ym2M+-kiL._SL500_.jpg", "8h 16m", 496, 4.8, 20000, 31.48, ["fiction", "fantasy"], ["best-seller", "top-rated", "full-cast", "series"], "The new full-cast edition of Harry Potter and the Sorcerer's Stone, with Hugh Laurie narrating and a complete ensemble bringing Hogwarts to life.", "2025-11-04", true,
    "Harry Potter and the Sorcerer's Stone (Full-Cast Edition) is the 2025 immersive production of the series opener, featuring Hugh Laurie as narrator and a full cast voicing every character.",
    "For Harry Potter fans who want the story in cinematic audio, and families who want to share the magic together. It solves the problem of choosing the best way to relisten to the series.",
    "Perfect for family road trips and evening listening; the full cast makes every scene vivid. A wonderful way to introduce the series to new listeners.",
    "Unlike single-narrator versions, this edition gives each character their own actor while Hugh Laurie anchors the storytelling. It turns the book into an audio drama.",
    "Absolutely. Start your free trial and hear Platform 9 3/4 like never before. This is the definitive way to start the series."),
  b("B0DG3M884R", "the-correspondent-virginia-evans", "The Correspondent: A Novel", "Virginia Evans", "Maggi-Meg Reed", "https://m.media-amazon.com/images/I/41FerlLzLNL._SL500_.jpg", "10h 0m", 600, 4.5, 3000, 19.80, ["fiction", "mystery-thriller"], ["new-release"], "The Correspondent is a tense novel about a journalist whose investigation into a powerful family uncovers a web of lies.", "2025-04-29", true,
    "The Correspondent by Virginia Evans is a 2025 suspense novel about a journalist chasing a story that threatens a powerful family. Maggi-Meg Reed narrates this 10-hour listen.",
    "For readers who love journalism thrillers and conspiracy-layered mysteries. It solves the problem of a fast, intelligent page-turner with real-world stakes.",
    "Great for commutes and evenings; the investigation structure keeps chapters tight. A quick, satisfying read.",
    "Evans combines career pressure with personal stakes, and Reed's narration keeps the tension sharp. A strong debut voice in suspense.",
    "Absolutely. Start your free trial and follow the story. Thriller fans will appreciate the momentum."),
  b("B0F151V9H2", "harry-potter-chamber-of-secrets-full-cast", "Harry Potter and the Chamber of Secrets (Full-Cast Edition)", "J.K. Rowling", "Hugh Laurie", "https://m.media-amazon.com/images/I/61p0qiVzZLL._SL500_.jpg", "12h 0m", 720, 4.8, 15000, 31.49, ["fiction", "fantasy"], ["best-seller", "top-rated", "full-cast", "series"], "The full-cast edition of Harry Potter and the Chamber of Secrets brings Hogwarts' second year to life with Hugh Laurie and an ensemble cast.", "2025-12-16", true,
    "Harry Potter and the Chamber of Secrets (Full-Cast Edition) is the immersive 2025 production of the second Potter book, with Hugh Laurie narrating and a full cast.",
    "For Potter fans collecting the new full-cast editions and families wanting cinematic audio. It solves the problem of a consistent, high-production series listening experience.",
    "Perfect for family listening and weekend marathons; the mystery of the Chamber is ideal for shared sessions.",
    "The ensemble format makes Dobby, the basilisk, and every Hogwarts voice feel fresh, while Laurie's narration keeps the story cohesive.",
    "Absolutely. Start your free trial and continue the full-cast journey. Fans will love hearing the Chamber come alive."),
  b("B0F14VX598", "harry-potter-deathly-hallows-full-cast", "Harry Potter and the Deathly Hallows (Full-Cast Edition)", "J.K. Rowling", "Hugh Laurie", "https://m.media-amazon.com/images/I/51JFEMoRTmL._SL500_.jpg", "21h 0m", 1260, 4.8, 10000, 47.24, ["fiction", "fantasy"], ["best-seller", "top-rated", "full-cast", "series"], "The full-cast finale of the Harry Potter series, bringing the Battle of Hogwarts to life with Hugh Laurie and an epic ensemble.", "2026-05-12", true,
    "Harry Potter and the Deathly Hallows (Full-Cast Edition) is the 2026 immersive production of the saga's finale, with Hugh Laurie narrating and a large cast. At 21 hours, it is the series' biggest production.",
    "For Potter fans completing the full-cast collection and anyone who wants an epic finale in audio. It solves the problem of experiencing the Battle of Hogwarts as an audio event.",
    "Made for marathon listening; the emotional and action-packed finale rewards long sessions. Outstanding value at 21 hours.",
    "The full-cast format gives the huge finale the theatrical scale it deserves, from the Horcrux hunt to the final battle.",
    "Absolutely. Start your free trial and end the journey in style. The full-cast finale is a must for series fans."),
  b("B0F155MX8X", "harry-potter-prisoner-of-azkaban-full-cast", "Harry Potter and the Prisoner of Azkaban (Full-Cast Edition)", "J.K. Rowling", "Hugh Laurie", "https://m.media-amazon.com/images/I/51KqTt1Fk1L._SL500_.jpg", "12h 0m", 720, 4.8, 12000, 31.49, ["fiction", "fantasy"], ["best-seller", "top-rated", "full-cast", "series"], "The full-cast edition of Harry Potter and the Prisoner of Azkaban brings Sirius Black and the Marauders to life.", "2026-01-13", true,
    "Harry Potter and the Prisoner of Azkaban (Full-Cast Edition) is the immersive 2026 production of the series' third book, with Hugh Laurie narrating and a full cast.",
    "For Potter fans building the full-cast set. It solves the problem of a consistent, cinematic way to revisit the Marauders' story.",
    "Great for family listening and evenings; the mystery of Sirius Black keeps everyone engaged.",
    "The ensemble gives Lupin, Sirius, and the Marauder-era flashbacks real depth, while Laurie's narration anchors the magic.",
    "Absolutely. Start your free trial and hear the Marauders' story anew. A fan-favorite installment gets a fan-favorite production."),
  b("B0F14Y9VTD", "harry-potter-half-blood-prince-full-cast", "Harry Potter and the Half-Blood Prince (Full-Cast Edition)", "J.K. Rowling", "Hugh Laurie", "https://m.media-amazon.com/images/I/51Pu7k4GKGL._SL500_.jpg", "18h 0m", 1080, 4.8, 10000, 47.24, ["fiction", "fantasy"], ["best-seller", "top-rated", "full-cast", "series"], "The full-cast edition of Harry Potter and the Half-Blood Prince brings the sixth year and Voldemort's secrets to vivid life.", "2026-04-14", true,
    "Harry Potter and the Half-Blood Prince (Full-Cast Edition) is the 2026 immersive production of the sixth Potter book, narrated by Hugh Laurie with a full cast.",
    "For Potter fans collecting the full-cast editions. It solves the problem of a cinematic way to revisit the series' darkest turning point.",
    "Perfect for family listening and weekend sessions; the Horcrux discoveries and the finale reward focused listening.",
    "The full cast brings Slughorn's parties, the Pensieve memories, and the emotional ending to life with new clarity.",
    "Absolutely. Start your free trial and experience the sixth year in full-cast form. The finale lands harder in audio."),
  b("B0FJP3TFG3", "stop-letting-everything-affect-you-chidiac", "Stop Letting Everything Affect You", "Daniel Chidiac", "Daniel Chidiac", "https://m.media-amazon.com/images/I/41i5tOpGyKL._SL500_.jpg", "6h 0m", 360, 4.5, 10000, 14.01, ["self-improvement"], ["top-rated", "mindset"], "Stop Letting Everything Affect You is a practical guide to breaking free from overthinking, emotional chaos, and self-sabotage.", "2025-07-24", true,
    "Stop Letting Everything Affect You by Daniel Chidiac is a self-development audiobook about managing emotions, overthinking, and self-sabotage. Chidiac narrates this 6-hour guide.",
    "For anyone who feels drained by other people's reactions or their own overthinking. It solves the problem of emotional reactivity with practical, repeatable tools.",
    "Perfect for commutes and morning walks; the short chapters make it easy to apply daily. A quick, actionable listen.",
    "Chidiac combines relatable personal stories with clear exercises, and his own narration makes the advice feel direct. It is a modern take on emotional resilience.",
    "Absolutely. Start your free trial and use the first tool today. It is a fast, practical listen for anyone feeling overwhelmed."),
  b("B0F154RT46", "harry-potter-order-of-phoenix-full-cast", "Harry Potter and the Order of the Phoenix (Full-Cast Edition)", "J.K. Rowling", "Hugh Laurie", "https://m.media-amazon.com/images/I/51qW73k+gWL._SL500_.jpg", "27h 0m", 1620, 4.8, 12000, 47.24, ["fiction", "fantasy"], ["best-seller", "top-rated", "full-cast", "series"], "The longest Harry Potter book gets the full-cast treatment: Order of the Phoenix comes alive with Hugh Laurie and an ensemble of voices.", "2026-03-10", true,
    "Harry Potter and the Order of the Phoenix (Full-Cast Edition) is the 2026 immersive production of the longest Potter novel, with Hugh Laurie narrating and a full cast. At 27 hours, it is a massive listen.",
    "For Potter fans who want the complete full-cast set, especially those who love the fifth book's darker tone. It solves the problem of a long book needing a dynamic production.",
    "Made for marathon listening; the 27-hour runtime is excellent value and rewards dedicated sessions.",
    "The full cast brings Dumbledore's Army, Dolores Umbridge, and the Department of Mysteries to life with theatrical energy.",
    "Absolutely. Start your free trial and take on the fifth year. At 27 hours, one credit buys an enormous production."),
  b("B0H2NCMHS6", "the-stone-sisters-margot-hunt", "The Stone Sisters", "Margot Hunt", "Therese Plummer", "https://m.media-amazon.com/images/I/51R0lzj5xmL._SL500_.jpg", "9h 0m", 540, 4.3, 4000, 18.30, ["mystery-thriller"], ["new-release"], "The Stone Sisters is a tense domestic thriller about three sisters reunited by a family secret that someone wants to keep buried.", "2026-07-23", true,
    "The Stone Sisters by Margot Hunt is a 2026 domestic thriller about three sisters drawn back together by a secret that threatens their family. Therese Plummer narrates.",
    "For fans of family-secret thrillers and character-driven suspense. It solves the problem of a listen that balances emotional stakes with twists.",
    "Great for commutes and evenings; the family dynamics keep the story moving. A quick, engaging listen.",
    "Hunt builds suspense from sibling bonds rather than just plot, and Plummer gives each sister a distinct voice. A fresh take on the domestic thriller.",
    "Absolutely. Start your free trial and join the sisters. The secret unfolds at just the right pace."),
  b("B0FY4X5ZFX", "biological-war-annie-jacobsen", "Biological War: A Scenario", "Annie Jacobsen", "Annie Jacobsen", "https://m.media-amazon.com/images/I/414ORR6XUCL._SL500_.jpg", "7h 0m", 420, 4.6, 6000, 21.60, ["history", "science"], ["new-release", "best-seller"], "Biological War is Annie Jacobsen's chilling scenario nonfiction about what a modern bioweapons attack could actually do.", "2026-07-28", true,
    "Biological War: A Scenario by Annie Jacobsen is a 2026 work of investigative scenario nonfiction, examining how a real bioweapons attack could unfold. Jacobsen narrates.",
    "For readers of nonfiction thrillers and anyone who loved her previous works like Operation Paperclip. It solves the problem of serious, well-researched listening about modern threats.",
    "Great for focused evenings; the scenario structure is gripping and informative. A powerful one-week listen.",
    "Jacobsen is one of the most respected investigative writers in audio, and her calm, direct narration makes the scenario feel disturbingly real.",
    "Absolutely. Start your free trial and hear the scenario unfold. It is journalism that reads like a thriller."),
  b("B0FZRJCQ48", "the-unknown-riley-sager", "The Unknown: A Novel", "Riley Sager", "Riley Sager", "https://m.media-amazon.com/images/I/51Sn5YxI+NL._SL500_.jpg", "10h 0m", 600, 4.6, 8000, 22.50, ["mystery-thriller"], ["new-release", "best-seller"], "The Unknown is Riley Sager's new twisty thriller, where a true-crime obsession turns deadly when the victim turns out to be someone she knows.", "2026-08-04", true,
    "The Unknown by Riley Sager is a 2026 psychological thriller about a true-crime enthusiast who discovers the next victim is someone close to her. Sager narrates his own novel.",
    "For thriller readers who love Sager's signature twists and meta true-crime themes. It solves the problem of finding the summer's most anticipated thriller.",
    "Perfect for evenings and weekends; the short chapters and constant misdirection make it hard to pause.",
    "Sager has a gift for making readers doubt everything, and narrating his own book adds a personal edge. A must-listen for thriller fans.",
    "Absolutely. Start your free trial and follow the obsession. You will guess wrong until the final twist."),
  b("B07RFSSYBH", "atomic-habits-james-clear", "Atomic Habits", "James Clear", "James Clear", "https://m.media-amazon.com/images/I/513Y5o-DYtL._SL500_.jpg", "5h 35m", 335, 4.8, 185000, 18.00, ["self-improvement"], ["best-seller", "top-rated"], "Atomic Habits by James Clear is the definitive practical guide to building good habits and breaking bad ones, narrated by the author.", "2018-10-16", false,
    "Atomic Habits by James Clear is the #1 New York Times bestseller about building better habits through small, repeatable changes. Clear narrates this 5.5-hour audiobook himself.",
    "For anyone who has tried and failed to change a habit, whether it is exercise, reading, or saving. It solves the problem of relying on motivation by building systems instead.",
    "Perfect for commutes; at 5.5 hours you can finish in a week. The short chapters make it easy to apply daily.",
    "Clear's four-step model (Cue, Craving, Response, Reward) is famously practical, and his own narration makes the advice feel personal. It is a modern self-improvement classic.",
    "Absolutely. Start your free trial and apply the first chapter's principles today. It is the rare self-help book that pays off immediately."),
  b("B0H85CK6QG", "the-chef-kl-slater", "The Chef", "K. L. Slater", "Annabel Scholey", "https://m.media-amazon.com/images/I/41J3Xu9eTNL._SL500_.jpg", "8h 0m", 480, 4.4, 6000, 19.32, ["mystery-thriller"], ["new-release"], "The Chef is K.L. Slater's new domestic thriller, where a cozy restaurant hides a dangerous obsession.", "2026-07-09", true,
    "The Chef by K.L. Slater is a 2026 domestic thriller set around a restaurant where an obsessive love turns toxic. Annabel Scholey narrates this 8-hour listen.",
    "For fans of domestic suspense and British thrillers. It solves the problem of a fast, tense listen with a chilling atmosphere.",
    "Great for commutes and evenings; the obsessive dynamics keep the tension high. A quick binge.",
    "Slater is a reliable voice in domestic suspense, and the restaurant setting gives the obsession an intimate, claustrophobic edge.",
    "Absolutely. Start your free trial and step into the kitchen. Thriller fans will be unsettled in the best way."),
  b("B0GW7DVH6S", "regime-change-haberman", "Regime Change: Inside the Imperial Presidency of Donald Trump", "Maggie Haberman", "Robert Petkoff", "https://m.media-amazon.com/images/I/511feNskpPL._SL500_.jpg", "15h 0m", 900, 4.5, 5000, 24.74, ["politics-social", "history"], ["new-release", "best-seller"], "Regime Change is Maggie Haberman's deeply reported account of the modern imperial presidency, from one of the most trusted political journalists in America.", "2026-06-23", true,
    "Regime Change by Maggie Haberman is a 2026 political history examining the expansion of presidential power through the Trump era. Robert Petkoff narrates this 15-hour work.",
    "For readers of political journalism and modern history who want deeply reported context. It solves the problem of understanding how the presidency changed.",
    "Great for long commutes and focused evenings; the reporting rewards attention. A substantial one-credit listen.",
    "Haberman's access and reporting are unmatched, and Petkoff's narration keeps the dense history engaging. It is an essential listen for political nonfiction fans.",
    "Absolutely. Start your free trial and follow the reporting. It reads like a Washington thriller."),
  b("B0D6NSD57S", "sunrise-on-the-reaping-collins", "Sunrise on the Reaping (The Hunger Games)", "Suzanne Collins", "Jefferson White", "https://m.media-amazon.com/images/I/41oFuJ88q6L._SL500_.jpg", "15h 24m", 924, 4.6, 60000, 22.29, ["teen-young-adult", "fiction"], ["best-seller", "top-rated", "series"], "Sunrise on the Reaping is the Hunger Games prequel following Haymitch Abernathy's brutal Games, 24 years before Katniss.", "2025-03-18", true,
    "Sunrise on the Reaping is Suzanne Collins' Hunger Games prequel, following Haymitch Abernathy through his own Games and rebellion. Jefferson White narrates this 15-hour audiobook.",
    "For Hunger Games fans and dystopian readers who want the origin of a beloved character. It solves the problem of finding a prequel that deepens the original story.",
    "Perfect for commutes and weekend sessions; the Games structure keeps the pace relentless. A strong two-week listen.",
    "Collins returns to the themes that made the series iconic, and White brings Haymitch's pain and wit to life. It is essential for Hunger Games readers.",
    "Absolutely. Start your free trial and enter Haymitch's Games. You will never read his character the same way again."),
  b("B06XPNVB4Q", "anxious-for-nothing-lucado", "Anxious for Nothing: Finding Calm in a Chaotic World", "Max Lucado", "Ben Holland", "https://m.media-amazon.com/images/I/61qeoMrqlSL._SL500_.jpg", "4h 30m", 270, 4.8, 10000, 18.89, ["religion-spirituality", "self-improvement"], ["top-rated", "quick-read"], "Anxious for Nothing is Max Lucado's gentle, faith-based guide to finding peace in a stressful world.", "2017-09-12", true,
    "Anxious for Nothing by Max Lucado is a faith-based guide to managing anxiety through biblical principles and practical habits. Ben Holland narrates this 4.5-hour audiobook.",
    "For anyone seeking calm amid stress, especially readers who want a faith-centered perspective. It solves the problem of spiritual comfort in anxious seasons.",
    "Perfect for mornings and short commutes; the gentle chapters make it easy to revisit. A quick, soothing listen.",
    "Lucado is one of the most beloved voices in faith-based encouragement, and the book's practical prayer-and-thought tools are simple to apply.",
    "Absolutely. Start your free trial and let the first chapter slow you down. It is a balm for anxious minds."),
  b("B0F6F84RLY", "my-husbands-wife-alice-feeney", "My Husband's Wife: A Novel", "Alice Feeney", "Bel Powley", "https://m.media-amazon.com/images/I/417dJ4I2GVL._SL500_.jpg", "9h 0m", 540, 4.4, 5000, 20.24, ["mystery-thriller"], ["new-release"], "My Husband's Wife is Alice Feeney's new thriller about a marriage built on secrets and the truth that destroys everything.", "2026-01-20", true,
    "My Husband's Wife by Alice Feeney is a 2026 psychological thriller about a marriage hiding secrets that slowly unravel. Bel Powley narrates this 9-hour listen.",
    "For fans of twisty domestic thrillers and unreliable narrators. It solves the problem of finding a sharp, unpredictable listen.",
    "Great for evenings and weekends; the short chapters and suspicion keep the pace tight. A fast binge.",
    "Feeney is known for killer twists, and Powley's narration adds a layer of intimate unease. A strong addition to her thriller catalog.",
    "Absolutely. Start your free trial and start doubting everything. Thriller fans will love the ride."),
  b("B0FB63LD1T", "her-cold-justice-dugoni", "Her Cold Justice: Keera Duggan, Book 3", "Robert Dugoni", "Saskia Maarleveld", "https://m.media-amazon.com/images/I/51lCzNMpiKL._SL500_.jpg", "10h 0m", 600, 4.7, 15000, 21.09, ["mystery-thriller"], ["best-seller", "series"], "Her Cold Justice is the third Keera Duggan legal thriller, pitting the Seattle lawyer against a cold case that threatens everything.", "2026-01-27", true,
    "Her Cold Justice is the third book in Robert Dugoni's Keera Duggan series, a legal thriller about a cold case with powerful enemies. Saskia Maarleveld narrates.",
    "For legal-thriller and procedural fans who love smart heroines and Seattle settings. It solves the problem of a reliable series with a strong female lead.",
    "Great for commutes and evenings; the courtroom and investigation threads keep the pace brisk. A solid weekly listen.",
    "Dugoni is a master of legal thrillers, and Keera is one of his most compelling protagonists. Maarleveld brings both toughness and vulnerability.",
    "Absolutely. Start your free trial and follow the cold case. New readers can jump in without reading the earlier books."),
  b("B0FF666V97", "unselected-journals-emma-m-lion-vol1", "The Unselected Journals of Emma M. Lion: Vol. 1", "Beth Brower", "Genevieve Gaunt", "https://m.media-amazon.com/images/I/51WEiHz1+wL._SL500_.jpg", "6h 30m", 390, 4.8, 20000, 13.62, ["fiction"], ["top-rated", "series", "cozy"], "The first volume of the beloved found-family Victorian London series, told through Emma M. Lion's witty, heartwarming journals.", "2025-08-14", true,
    "The Unselected Journals of Emma M. Lion Vol. 1 is the charming opening of Beth Brower's Victorian London series, told through the heroine's diary. Genevieve Gaunt narrates.",
    "For readers who love cozy, character-driven historical fiction and diary formats. It solves the problem of finding a warm, witty series with real heart.",
    "Perfect for short commutes and cozy evenings; the journal entries make it easy to pause and resume. A gentle, quick listen.",
    "Brower's journal style and Gaunt's narration create an intimate, witty voice that has built a devoted following. It is comfort listening at its best.",
    "Absolutely. Start your free trial and open the first journal. You will want to collect every volume."),
  b("B00X0TKUS0", "48-laws-of-power-greene", "48 Laws of Power", "Robert Greene", "Richard Poe", "https://m.media-amazon.com/images/I/41dTDMW9IhL._SL500_.jpg", "21h 20m", 1280, 4.6, 30000, 28.32, ["business", "self-improvement"], ["classic", "top-rated", "long-read"], "The 48 Laws of Power is Robert Greene's controversial classic on strategy and influence, drawing on centuries of history.", "2015-05-01", true,
    "The 48 Laws of Power by Robert Greene is a modern classic of strategy and psychology, distilling lessons from history into 48 rules. Richard Poe narrates this 21-hour audiobook.",
    "For ambitious professionals, leaders, and readers fascinated by power dynamics. It solves the problem of understanding influence with memorable, historically grounded laws.",
    "Great for commutes and focused sessions; each law is self-contained, making it easy to digest one at a time. Excellent value at 21 hours.",
    "Greene's research spans centuries and cultures, and Poe's measured narration gives each law weight. It is one of the most referenced strategy books in business and entertainment.",
    "Absolutely. Start your free trial and learn one law per commute. It is a dense, rewarding listen for anyone navigating power."),
];

const data = JSON.parse(fs.readFileSync(BOOKS_PATH, "utf-8"));
const existing = new Set(data.books.map((b) => b.asin));
let added = 0;
for (const book of NEW_BOOKS) {
  if (!existing.has(book.asin)) {
    data.books.push(book);
    existing.add(book.asin);
    added++;
    console.log("Added " + book.slug);
  } else {
    console.log("Skip existing " + book.asin);
  }
}
fs.writeFileSync(BOOKS_PATH, JSON.stringify(data, null, 2));
console.log("Batch 4 complete. Added " + added + " books. Total: " + data.books.length);
